### ISSUE TITLE
[Bug] Build from source, build_cuda.sh fail with environment conflict

### ISSUE THREAD

**Issue by hubert0527** [apache/tvm#10134]
### Expected behavior

I followed the [install/build instruction](https://tvm.apache.org/docs/install/from_source.html) to build TVM with CUDA11.1. And failed at the following step:
```
conda build --output-folder=conda/pkg  conda/recipe
# Run conda/build_cuda.sh to build with cuda enabled     <= Failed here
conda install tvm -c ./conda/pkg
```

### Actual behavior

conda complains about the environmental conflicts. The conda environment was freshly created with `conda env create --file conda/build-environment.yaml` as instructed. I have tried building it under two different machines, but both of them fail in a similar way. Could this be a problem with CUDA 11.1?

P.S. I am particularly sticking with CUDA 11.x since CUDA 10 had some performance regression issues with RTX3090 GPUs.

### Environment

OS: `Ubuntu 18.04`

TVM version: `latest git clone`

CUDA (`nvcc -V`):
```
Cuda compilation tools, release 11.1, V11.1.74
Build cuda_11.1.TC455_06.29069683_0
```

g++ version: 
```
g++ (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
```

python version: `3.8.5`
conda version: `4.11.0`

### Full error message / env conflict / stack trace

```
No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.11
WARNING:conda_build.metadata:No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.11
Copying /home/hubert/bin/tvm-s6 to /home/hubert/miniconda3/envs/tvm6/conda-bld/tvm-package_1643754272410/work/
Adding in variants from internal_defaults
INFO:conda_build.variants:Adding in variants from internal_defaults
Adding in variants from /home/hubert/bin/tvm-s6/conda/recipe/conda_build_config.yaml
INFO:conda_build.variants:Adding in variants from /home/hubert/bin/tvm-s6/conda/recipe/conda_build_config.yaml
Adding in variants from argument_variants
INFO:conda_build.variants:Adding in variants from argument_variants
Attempting to finalize metadata for tvm-cu11-libs
INFO:conda_build.metadata:Attempting to finalize metadata for tvm-cu11-libs
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working...
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

Leaving build/test directories:
  Work:
 /home/hubert/miniconda3/envs/tvm6/conda-bld/work
  Test:
 /home/hubert/miniconda3/envs/tvm6/conda-bld/test_tmp
Leaving build/test environments:
  Test:
source activate  /home/hubert/miniconda3/envs/tvm6/conda-bld/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p
lacehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold
  Build:
source activate  /home/hubert/miniconda3/envs/tvm6/conda-bld/_build_env
```

```
Traceback (most recent call last):
  File "/home/hubert/miniconda3/envs/tvm6/lib/python3.8/site-packages/conda_build/environ.py", line 798, in get_install_actions
    actions = install_actions(prefix, index, specs, force=True)
  File "/home/hubert/miniconda3/envs/tvm6/lib/python3.8/site-packages/conda/common/io.py", line 88, in decorated
    return f(*args, **kwds)
  File "/home/hubert/miniconda3/envs/tvm6/lib/python3.8/site-packages/conda/plan.py", line 474, in install_actions
    txn = solver.solve_for_transaction(prune=prune, ignore_pinned=not pinned)
  File "/home/hubert/miniconda3/envs/tvm6/lib/python3.8/site-packages/conda/core/solve.py", line 114, in solve_for_transaction
    unlink_precs, link_precs = self.solve_for_diff(update_modifier, deps_modifier,
  File "/home/hubert/miniconda3/envs/tvm6/lib/python3.8/site-packages/conda/core/solve.py", line 157, in solve_for_diff
    final_precs = self.solve_final_state(update_modifier, deps_modifier, prune, ignore_pinned,
  File "/home/hubert/miniconda3/envs/tvm6/lib/python3.8/site-packages/conda/core/solve.py", line 281, in solve_final_state
    ssc = self._run_sat(ssc)
  File "/home/hubert/miniconda3/envs/tvm6/lib/python3.8/site-packages/conda/common/io.py", line 88, in decorated
    return f(*args, **kwds)
  File "/home/hubert/miniconda3/envs/tvm6/lib/python3.8/site-packages/conda/core/solve.py", line 815, in _run_sat
    ssc.solution_precs = ssc.r.solve(tuple(final_environment_specs),
  File "/home/hubert/miniconda3/envs/tvm6/lib/python3.8/site-packages/conda/common/io.py", line 88, in decorated
    return f(*args, **kwds)
  File "/home/hubert/miniconda3/envs/tvm6/lib/python3.8/site-packages/conda/resolve.py", line 1322, in solve
    self.find_conflicts(specs, specs_to_add, history_specs)
  File "/home/hubert/miniconda3/envs/tvm6/lib/python3.8/site-packages/conda/resolve.py", line 352, in find_conflicts
    raise UnsatisfiableError(bad_deps, strict=strict_channel_priority)
conda.exceptions.UnsatisfiableError: The following specifications were found to be incompatible with each other:
```

```
Output in format: Requested package -> Available versions

Package libstdcxx-ng conflicts for:
cudnn[version='>=7.6.0,<8.0a0'] -> cudatoolkit[version='>=10.2,<10.3'] -> libstdcxx-ng[version='>=7.3.0']
llvmdev==10.0.0 -> libstdcxx-ng[version='>=7.3.0']
cudatoolkit[version='>=11,<12.0a0'] -> libstdcxx-ng[version='>=7.3.0|>=9.3.0']

Package _openmp_mutex conflicts for:
cudatoolkit[version='>=11,<12.0a0'] -> libgcc-ng[version='>=9.3.0'] -> _openmp_mutex[version='>=4.5']
llvmdev==10.0.0 -> libgcc-ng[version='>=7.3.0'] -> _openmp_mutex[version='>=4.5']
zlib -> libgcc-ng[version='>=7.5.0'] -> _openmp_mutex[version='>=4.5']

Package libgcc-ng conflicts for:
zlib -> libgcc-ng[version='>=7.2.0|>=7.3.0|>=7.5.0']
cudnn[version='>=7.6.0,<8.0a0'] -> cudatoolkit[version='>=10.2,<10.3'] -> libgcc-ng[version='>=7.3.0']
llvmdev==10.0.0 -> libgcc-ng[version='>=7.3.0']
cudatoolkit[version='>=11,<12.0a0'] -> libgcc-ng[version='>=7.3.0|>=9.3.0']

Package cudatoolkit conflicts for:
cudatoolkit[version='>=11,<12.0a0']
cudnn[version='>=7.6.0,<8.0a0'] -> cudatoolkit[version='>=10.0,<10.1|>=10.1,<10.2|>=9.0,<9.1|>=9.2,<9.3|>=10.2,<10.3']The following specifications were found to be incompatible with your syste
m:

  - feature:/linux-64::__glibc==2.27=0
  - cudatoolkit[version='>=11,<12.0a0'] -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - llvmdev==10.0.0 -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - zlib -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']

Your installed version is: 2.27
```

```
Traceback (most recent call last):
  File "/home/hubert/miniconda3/envs/tvm6/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/home/hubert/miniconda3/envs/tvm6/lib/python3.8/site-packages/conda_build/cli/main_build.py", line 474, in main
    execute(sys.argv[1:])
  File "/home/hubert/miniconda3/envs/tvm6/lib/python3.8/site-packages/conda_build/cli/main_build.py", line 463, in execute
    outputs = api.build(args.recipe, post=args.post, test_run_post=args.test_run_post,
  File "/home/hubert/miniconda3/envs/tvm6/lib/python3.8/site-packages/conda_build/api.py", line 186, in build
    return build_tree(
  File "/home/hubert/miniconda3/envs/tvm6/lib/python3.8/site-packages/conda_build/build.py", line 3008, in build_tree
    packages_from_this = build(metadata, stats,
  File "/home/hubert/miniconda3/envs/tvm6/lib/python3.8/site-packages/conda_build/build.py", line 1971, in build
    output_metas = expand_outputs([(m, need_source_download, need_reparse_in_env)])
  File "/home/hubert/miniconda3/envs/tvm6/lib/python3.8/site-packages/conda_build/render.py", line 757, in expand_outputs
    for (output_dict, m) in deepcopy(_m).get_output_metadata_set(permit_unsatisfiable_variants=False):
  File "/home/hubert/miniconda3/envs/tvm6/lib/python3.8/site-packages/conda_build/metadata.py", line 2063, in get_output_metadata_set
    conda_packages = finalize_outputs_pass(ref_metadata, conda_packages, pass_no=0,
  File "/home/hubert/miniconda3/envs/tvm6/lib/python3.8/site-packages/conda_build/metadata.py", line 735, in finalize_outputs_pass
    fm = finalize_metadata(om, parent_metadata=parent_metadata,
  File "/home/hubert/miniconda3/envs/tvm6/lib/python3.8/site-packages/conda_build/render.py", line 530, in finalize_metadata
    m = parent_metadata.get_output_metadata(m.get_rendered_output(m.name()))
  File "/home/hubert/miniconda3/envs/tvm6/lib/python3.8/site-packages/conda_build/metadata.py", line 2122, in get_rendered_output
    for output_ in self.get_rendered_outputs_section(
  File "/home/hubert/miniconda3/envs/tvm6/lib/python3.8/site-packages/conda_build/metadata.py", line 2108, in get_rendered_outputs_section
    outputs = (yaml.safe_load(self._get_contents(permit_undefined_jinja=permit_undefined_jinja,
  File "/home/hubert/miniconda3/envs/tvm6/lib/python3.8/site-packages/conda_build/metadata.py", line 1544, in _get_contents
    rendered = template.render(environment=env)
  File "/home/hubert/miniconda3/envs/tvm6/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/hubert/miniconda3/envs/tvm6/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/hubert/miniconda3/envs/tvm6/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 21, in top-level template code
  File "/home/hubert/miniconda3/envs/tvm6/lib/python3.8/site-packages/conda_build/jinja_context.py", line 230, in pin_compatible
    pins, _, _ = get_env_dependencies(m, 'host', m.config.variant)
  File "/home/hubert/miniconda3/envs/tvm6/lib/python3.8/site-packages/conda_build/render.py", line 139, in get_env_dependencies
    actions = environ.get_install_actions(tmpdir, tuple(dependencies), env,
  File "/home/hubert/miniconda3/envs/tvm6/lib/python3.8/site-packages/conda_build/environ.py", line 800, in get_install_actions
    raise DependencyNeedsBuildingError(exc, subdir=subdir)
conda_build.exceptions.DependencyNeedsBuildingError: Unsatisfiable dependencies for platform linux-64: {"libgcc-ng[version='>=7.2.0|>=7.3.0|>=7.5.0']", "__glibc[version='>=2.17']", "_openmp_mutex[version='>=4.5']", "libgcc-ng[version='>=7.3.0']", "libgcc-ng[version='>=7.3.0|>=9.3.0']", 'feature:/linux-64::__glibc==2.27=0', "libstdcxx-ng[version='>=7.3.0']", "libstdcxx-ng[version='>=7.3.0|>=9.3.0']"}
```
My conda environment:
```
# packages in environment at /home/hubert/miniconda3/envs/tvm6:
#
# Name                    Version                   Build  Channel
attrs                     20.2.0                     py_0    anaconda
beautifulsoup4            4.9.3              pyhb0f4dca_0    anaconda
blas                      1.0                         mkl    anaconda
brotlipy                  0.7.0           py38h7b6447c_1000    anaconda
bzip2                     1.0.8                h7b6447c_0    anaconda
ca-certificates           2020.10.14                    0    anaconda
certifi                   2020.6.20                py38_0    anaconda
cffi                      1.14.3           py38he30daa8_0    anaconda
chardet                   3.0.4                 py38_1003    anaconda
cmake                     3.14.0               h52cb24c_0    anaconda
conda                     4.9.0                    py38_0    anaconda
conda-build               3.20.4                   py38_1    anaconda
conda-package-handling    1.7.2            py38h03888b9_0    anaconda
cryptography              3.1.1            py38h1ba5d50_0    anaconda
cython                    0.29.21          py38he6710b0_0    anaconda
expat                     2.2.10               he6710b0_2    anaconda
filelock                  3.0.12                     py_0    anaconda
freetype                  2.10.4               h5ab3b9f_0    anaconda
git                       2.23.0          pl526hacde149_0    anaconda
glob2                     0.7                        py_0    anaconda
icu                       58.2                 he6710b0_3    anaconda
idna                      2.10                       py_0    anaconda
iniconfig                 1.1.1                      py_0    anaconda
intel-openmp              2020.2                      254    anaconda
jinja2                    2.11.2                     py_0    anaconda
jpeg                      9b                   habf39ab_1    anaconda
krb5                      1.18.2               h173b8e3_0    anaconda
lcms2                     2.11                 h396b838_0    anaconda
ld_impl_linux-64          2.33.1               h53a641e_7    anaconda
libarchive                3.4.2                h62408e4_0    anaconda
libcurl                   7.71.1               h20c2e04_1    anaconda
libedit                   3.1.20191231         h14c3975_1    anaconda
libffi                    3.3                  he6710b0_2    anaconda
libgcc-ng                 9.1.0                hdf63c60_0    anaconda
libgfortran-ng            7.3.0                hdf63c60_0    anaconda
liblief                   0.10.1               he6710b0_0    anaconda
libllvm10                 10.0.0               h4a3c616_1    anaconda
libpng                    1.6.37               hbc83047_0    anaconda
libssh2                   1.9.0                h1ba5d50_1    anaconda
libstdcxx-ng              9.1.0                hdf63c60_0    anaconda
libtiff                   4.1.0                h2733197_1    anaconda
libxml2                   2.9.10               hb55368b_3    anaconda
llvm-tools                10.0.0               h4a3c616_1    anaconda
llvmdev                   10.0.0               h4a3c616_1    anaconda
lz4-c                     1.9.2                heb0550a_3    anaconda
make                      4.2.1                h1bed415_1    anaconda
markupsafe                1.1.1            py38h7b6447c_0    anaconda
mkl                       2019.4                      243    anaconda
mkl-service               2.3.0            py38he904b0f_0    anaconda
mkl_fft                   1.2.0            py38h23d657b_0    anaconda
mkl_random                1.1.0            py38h962f231_0    anaconda
more-itertools            8.5.0                      py_0    anaconda
ncurses                   6.2                  he6710b0_1    anaconda
numpy                     1.19.1           py38hbc911f0_0    anaconda
numpy-base                1.19.1           py38hfa32c7d_0    anaconda
olefile                   0.46                       py_0    anaconda
openssl                   1.1.1h               h7b6447c_0    anaconda
packaging                 20.4                       py_0    anaconda
patchelf                  0.12                 he6710b0_0    anaconda
pcre                      8.44                 he6710b0_0    anaconda
perl                      5.26.2               h14c3975_0    anaconda
pillow                    8.0.0            py38h9a89aac_0    anaconda
pip                       20.2.4                   py38_0    anaconda
pkginfo                   1.6.0                    py38_0    anaconda
pluggy                    0.13.1                   py38_0    anaconda
psutil                    5.7.2            py38h7b6447c_0    anaconda
py                        1.9.0                      py_0    anaconda
py-lief                   0.10.1           py38h403a769_0    anaconda
pycosat                   0.6.3            py38h7b6447c_1    anaconda
pycparser                 2.20                       py_2    anaconda
pyopenssl                 19.1.0                     py_1    anaconda
pyparsing                 2.4.7                      py_0    anaconda
pysocks                   1.7.1                    py38_0    anaconda
pytest                    6.1.1                    py38_0    anaconda
python                    3.8.5                h7579374_1    anaconda
python-libarchive-c       2.9                        py_0    anaconda
pytz                      2020.1                     py_0    anaconda
pyyaml                    5.3.1            py38h7b6447c_1    anaconda
readline                  8.0                  h7b6447c_0    anaconda
requests                  2.24.0                     py_0    anaconda
rhash                     1.4.0                h1ba5d50_0    anaconda
ripgrep                   12.1.1                        0    anaconda
ruamel_yaml               0.15.87          py38h7b6447c_1    anaconda
scipy                     1.5.2            py38h0b6359f_0    anaconda
setuptools                50.3.0           py38hb0f4dca_1    anaconda
six                       1.15.0                     py_0    anaconda
soupsieve                 2.0.1                      py_0    anaconda
sqlite                    3.33.0               h62c20be_0    anaconda
tk                        8.6.10               hbc83047_0    anaconda
toml                      0.10.1                     py_0    anaconda
tqdm                      4.50.2                     py_0    anaconda
urllib3                   1.25.11                    py_0    anaconda
wheel                     0.35.1                     py_0    anaconda
xz                        5.2.5                h7b6447c_0    anaconda
yaml                      0.2.5                h7b6447c_0    anaconda
zlib                      1.2.11               h7b6447c_3    anaconda
zstd                      1.4.4                h0b5b093_3    anaconda
```

**Comment by LyricZhao** [comment]
Same error with me (CUDA 11.2 + Miniconda). Downgrading to 10.2 works but not a fancy solution.

**Comment by LyricZhao** [comment]
In `conda/recipe/meta.yaml`, the version requirement for `cudnn` is from `>=7.6.0` (`lower_bound`) to `<8` (bounded by `max_pin`), while cuDNN 7 requires `cudatoolkit` version `<11`.

Simply changing `{{ pin_compatible('cudnn', lower_bound='7.6.0', max_pin='x') }}` into `cudnn` (2 lines) works for me.

@hubert0527

**Comment by masahi** [comment]
I assume this is fixed by https://github.com/apache/tvm/pull/10201

**Comment by hubert0527** [comment]
Sorry for the late reply, was a bit busy lately.
I have confirmed the issue on my side is addressed with the solution. Thanks for the amazing work from @LyricZhao !
