### ISSUE TITLE
[ci] conda build fails with connection errors

### ISSUE THREAD

**Issue by driazati** [apache/tvm#11401]
Failed on main for https://github.com/apache/tvm/commit/0274d8e1f124cecc159abf3234251bf010784581
https://github.com/apache/tvm/runs/6529970442?check_suite_focus=true

```
No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.16
WARNING:conda_build.metadata:No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.16
INFO:conda_build.variants:Adding in variants from internal_defaults
Copying D:\a\tvm\tvm to C:\Miniconda\envs\tvm-build\conda-bld\tvm-package_16530[7](https://github.com/apache/tvm/runs/6529970442?check_suite_focus=true#step:4:8)2260921\work\
INFO:conda_build.variants:Adding in variants from D:\a\tvm\tvm\conda\recipe\conda_build_config.yaml
Adding in variants from internal_defaults
Adding in variants from D:\a\tvm\tvm\conda\recipe\conda_build_config.yaml
INFO:conda_build.metadata:Attempting to finalize metadata for tvm-libs
Attempting to finalize metadata for tvm-libs
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): repo.anaconda.com:443
DEBUG:urllib3.connectionpool:https://repo.anaconda.com:443 "GET /pkgs/main/win-64/repodata.json HTTP/1.1" 304 0
DEBUG:urllib3.connectionpool:https://repo.anaconda.com:443 "GET /pkgs/main/noarch/repodata.json HTTP/1.1" 304 0
DEBUG:urllib3.connectionpool:https://repo.anaconda.com:443 "GET /pkgs/r/win-64/repodata.json HTTP/1.1" 304 0
DEBUG:urllib3.connectionpool:https://repo.anaconda.com:443 "GET /pkgs/r/noarch/repodata.json HTTP/1.1" 304 0
DEBUG:urllib3.connectionpool:https://repo.anaconda.com:443 "GET /pkgs/msys2/win-64/repodata.json HTTP/1.1" 304 0
DEBUG:urllib3.connectionpool:https://repo.anaconda.com:443 "GET /pkgs/msys2/noarch/repodata.json HTTP/1.1" 304 0
DEBUG:urllib3.connectionpool:https://repo.anaconda.com:443 "GET /pkgs/msys2/channeldata.json HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://repo.anaconda.com:443 "GET /pkgs/main/channeldata.json HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://repo.anaconda.com:443 "GET /pkgs/r/channeldata.json HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): conda.anaconda.org:443
DEBUG:urllib3.connectionpool:https://conda.anaconda.org:443 "GET /conda-forge/channeldata.json HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://conda.anaconda.org:443 "GET /anaconda/channeldata.json HTTP/1.1" 200 None
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done
DEBUG:urllib3.connectionpool:https://conda.anaconda.org:443 "GET /anaconda/win-64/cmake-3.22.1-h9ad04ae_0.tar.bz2 HTTP/1.1" 200 11[8](https://github.com/apache/tvm/runs/6529970442?check_suite_focus=true#step:4:9)85185
Traceback (most recent call last):
  File "C:\Miniconda\envs\tvm-build\Scripts\conda-build-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Miniconda\envs\tvm-build\lib\site-packages\conda_build\cli\main_build.py", line 488, in main
    execute(sys.argv[1:])
  File "C:\Miniconda\envs\tvm-build\lib\site-packages\conda_build\cli\main_build.py", line 47[9](https://github.com/apache/tvm/runs/6529970442?check_suite_focus=true#step:4:10), in execute
    verify=args.verify, variants=args.variants, cache_dir=args.cache_dir)
  File "C:\Miniconda\envs\tvm-build\lib\site-packages\conda_build\api.py", line 195, in build
    variants=variants
  File "C:\Miniconda\envs\tvm-build\lib\site-packages\conda_build\build.py", line 3093, in build_tree
    notest=notest,
  File "C:\Miniconda\envs\tvm-build\lib\site-packages\conda_build\build.py", line 2051, in build
    output_metas = expand_outputs([(m, need_source_download, need_reparse_in_env)])
  File "C:\Miniconda\envs\tvm-build\lib\site-packages\conda_build\render.py", line 788, in expand_outputs
    for (output_dict, m) in deepcopy(_m).get_output_metadata_set(permit_unsatisfiable_variants=False):
  File "C:\Miniconda\envs\tvm-build\lib\site-packages\conda_build\metadata.py", line 2122, in get_output_metadata_set
    bypass_env_check=bypass_env_check)
  File "C:\Miniconda\envs\tvm-build\lib\site-packages\conda_build\metadata.py", line 782, in finalize_outputs_pass
    permit_unsatisfiable_variants=permit_unsatisfiable_variants)
  File "C:\Miniconda\envs\tvm-build\lib\site-packages\conda_build\render.py", line 548, in finalize_metadata
    exclude_pattern)
  File "C:\Miniconda\envs\tvm-build\lib\site-packages\conda_build\render.py", line 387, in add_upstream_pins
    permit_unsatisfiable_variants, exclude_pattern)
  File "C:\Miniconda\envs\tvm-build\lib\site-packages\conda_build\render.py", line 378, in _read_upstream_pin_files
    extra_run_specs = get_upstream_pins(m, actions, env)
  File "C:\Miniconda\envs\tvm-build\lib\site-packages\conda_build\render.py", line 364, in get_upstream_pins
    loc, dist = execute_download_actions(m, actions, env=env, package_subset=pkg)[pkg]
  File "C:\Miniconda\envs\tvm-build\lib\site-packages\conda_build\render.py", line 329, in execute_download_actions
    pfe.execute()
  File "C:\Miniconda\envs\tvm-build\lib\site-packages\conda\core\package_cache_data.py", line 654, in execute
    raise CondaMultiError(exceptions)
conda.CondaMultiError: ("Connection broken: ConnectionResetError([10](https://github.com/apache/tvm/runs/6529970442?check_suite_focus=true#step:4:11)0[54](https://github.com/apache/tvm/runs/6529970442?check_suite_focus=true#step:4:55), 'An existing connection was forcibly closed by the remote host', None, 10054, None)", ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
```

cc @Mousius @areusch

**Comment by driazati** [comment]
fixed by #12058
