### ISSUE TITLE
[Bug] python.contrib.test_onnx.test_resize numerical accuracy issue

### ISSUE THREAD

**Issue by leandron** [apache/tvm#12567]
While working to enable Integration tests in AArch64 with ONNX and Torch installed (which is currently a blind spot in our CI, see https://github.com/apache/tvm/issues/12529), I'm seeing `python.contrib.test_onnx.test_resize` failing with an accuracy error. According to some tests locally, the issue reproduces consistently in x86 and AArch64.

I'm creating this issue so that we can investigate the numerical accuracy issue separately, but for now, I'm marking this test as an `xfail`.

Steps to reproduce:
1. Starting from a `ci_cpu` image, run the ONNX installation script (https://github.com/apache/tvm/blob/989e5a11285503716c2033f4e56f1bba6b6d00c7/docker/install/ubuntu_install_onnx.sh)
2. Run the test `python.contrib.test_onnx.test_resize`

This is the error message I see:
```
def test_resize():
        """Resize unit test."""
    
        def verify_resize(dshape, outsize, method, coord_trans, rounding_method, dtype="float32"):
            x = relay.var("x", relay.ty.TensorType(dshape, dtype))
            y = relay.image.resize2d(
                x,
                outsize,
                None,
                layout="NCHW",
                method=method,
                coordinate_transformation_mode=coord_trans,
                rounding_method=rounding_method,
            )
            func = relay.Function([x], y)
            x_data = np.random.uniform(size=dshape).astype(dtype)
            verify_results(func, [x_data], "test_resize", rtol=1e-4, atol=1e-4)
    
        method = ["nearest_neighbor", "linear", "cubic"]
        coord_trans = ["half_pixel", "align_corners", "asymmetric"]
        rounding_method = ["round", "floor", "ceil"]
    
        isize = (1, 3, 480, 640)
    
        # Downsample
        osize = (240, 320)
        for i in method:
            for j in coord_trans:
                for k in rounding_method:
                    if (i == "nearest_neighbor" and j == "align_corners") or (
                        i == "cubic" and j in ["half_pixel", "align_corners"]
                    ):
                        continue
                    verify_resize(isize, osize, method=i, coord_trans=j, rounding_method=k)
    
        # Upsample
        osize = (960, 1280)
        for i in method:
            for j in coord_trans:
                for k in rounding_method:
                    if (i == "nearest_neighbor" and j == "align_corners") or (i == "cubic"):
                        continue
>                   verify_resize(isize, osize, method=i, coord_trans=j, rounding_method=k)

tests/python/contrib/test_onnx.py:700: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
tests/python/contrib/test_onnx.py:674: in verify_resize
    verify_results(func, [x_data], "test_resize", rtol=1e-4, atol=1e-4)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

relay_func = fn (%x: Tensor[(1, 3, 480, 640), float32]) {
  image.resize2d(%x, size=[960, 1280], roi=[0f, 0f, 0f, 0f], method="nearest_neighbor", coordinate_transformation_mode="asymmetric")
}
indata = [array([[[[0.07992046, 0.10136255, 0.00943371, ..., 0.6083984 ,
          0.80598825, 0.8000824 ],
         [0.6850799...],
         [0.47949922, 0.5546733 , 0.77905625, ..., 0.5419391 ,
          0.09121019, 0.5444949 ]]]], dtype=float32)]
test_name = 'test_resize', rtol = 0.0001, atol = 0.0001, is_dyn = False

    def verify_results(relay_func, indata, test_name, rtol=1e-7, atol=0, is_dyn=False):
        relay_results = run_relay(relay_func, indata, is_dyn)
        onnx_results = run_onnx(func_to_onnx(relay_func, test_name), indata)
    
        for relay_res, onnx_res in zip(relay_results, onnx_results):
>           np.testing.assert_allclose(relay_res, onnx_res, rtol=rtol, atol=atol)
E           AssertionError: 
E           Not equal to tolerance rtol=0.0001, atol=0.0001
E           
E           Mismatched elements: 2760564 / 3686400 (74.9%)
E           Max absolute difference: 0.99967563
E           Max relative difference: 5434130.5
E            x: array([[[[0.07992 , 0.07992 , 0.101363, ..., 0.805988, 0.800082,
E                     0.800082],
E                    [0.07992 , 0.07992 , 0.101363, ..., 0.805988, 0.800082,...
E            y: array([[[[0.07992 , 0.101363, 0.101363, ..., 0.800082, 0.800082,
E                     0.800082],
E                    [0.68508 , 0.172607, 0.172607, ..., 0.060676, 0.060676,...

tests/python/contrib/test_onnx.py:69: AssertionError
```

cc @ashutosh-arm

**Comment by Jay-sanjay** [comment]
sir is the issue resolved on want to work on can you assign it to me

**Comment by lhutton1** [comment]
Hi @Jay-sanjay, it seems like there is still an issue, see https://github.com/apache/tvm/blob/6e79f64108b26b504089354cfce5e182001a70d1/tests/python/contrib/test_onnx.py#L658. Please feel free to take a look, I'll be happy to help review

**Comment by gessha** [comment]
I was trying to reproduce the bug but I got stuck. Do you know what I did wrong?

I built the tvm.ti_cpu container using 
`~/projects/tvm$ ./docker/build.sh ci_cpu`

As per @leandron's instructions I tried installing onnx but it seems like it was unnecessary is it's already installed in the last lines of the tvm.ci_cpu Docker file:
https://github.com/apache/tvm/blob/022299b51fa71c42f180b0c8e3afcac4eb50d71d/docker/Dockerfile.ci_cpu#L149-L151

I enter the container using `./docker/bash.sh tvm.ci_cpu -it bash`:

Then I tried running the test
`pytest ./tests/python/contrib/test_onnx.py::test_resize`

but I got the following error:

```
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/venv/apache-tvm-py3.8/lib/python3.8/site-packages/_pytest/main.py", line 266, in wrap_session
INTERNALERROR>     config._do_configure()
INTERNALERROR>   File "/venv/apache-tvm-py3.8/lib/python3.8/site-packages/_pytest/config/__init__.py", line 1054, in _do_configure
INTERNALERROR>     self.hook.pytest_configure.call_historic(kwargs=dict(config=self))
INTERNALERROR>   File "/venv/apache-tvm-py3.8/lib/python3.8/site-packages/pluggy/_hooks.py", line 514, in call_historic
INTERNALERROR>     res = self._hookexec(self.name, self._hookimpls, kwargs, False)
INTERNALERROR>   File "/venv/apache-tvm-py3.8/lib/python3.8/site-packages/pluggy/_manager.py", line 115, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>   File "/venv/apache-tvm-py3.8/lib/python3.8/site-packages/pluggy/_callers.py", line 113, in _multicall
INTERNALERROR>     raise exception.with_traceback(exception.__traceback__)
INTERNALERROR>   File "/venv/apache-tvm-py3.8/lib/python3.8/site-packages/pluggy/_callers.py", line 77, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/georgi/projects/tvm/python/tvm/testing/plugin.py", line 70, in pytest_configure
INTERNALERROR>     print("enabled targets:", "; ".join(map(lambda x: x[0], utils.enabled_targets())))
INTERNALERROR>   File "/home/georgi/projects/tvm/python/tvm/testing/utils.py", line 526, in enabled_targets
INTERNALERROR>     return [(t["target"], tvm.device(t["target"])) for t in _get_targets() if t["is_runnable"]]
INTERNALERROR>   File "/home/georgi/projects/tvm/python/tvm/testing/utils.py", line 445, in _get_targets
INTERNALERROR>     raise TVMError(
INTERNALERROR> tvm._ffi.base.TVMError: None of the following targets are supported by this build of TVM: ['llvm', 'cuda', 'nvptx', 'vulkan -from_device=0', 'opencl', 'opencl -device=mali,aocl_sw_emu', 'opencl -device=intel_graphics', 'metal', 'rocm', 'hexagon']. Try setting TVM_TEST_TARGETS to a supported target. Cannot default to llvm, as it is not enabled.
```

**Comment by lhutton1** [comment]
Hi @gessha, I suspect you need to build tvm with LLVM support. Can you try adding something like the following to config.cmake:
```
set(USE_LLVM llvm-config-16)
```
and then rebuilding.
