### ISSUE TITLE
[Bug] Cannot find function tvm.contrib.cudnn.conv2d.forward

### ISSUE THREAD

**Issue by wangzy0327** [apache/tvm#12843]
### Expected behavior

I want to using cudnn libraies in relay

### Actual behavior

I recompiled tvm with USE_CUDNN config successfully

![9dbe7401f346867f5bf02da96e00031](https://user-images.githubusercontent.com/22990858/191202252-babcc033-c22a-4637-a327-e3823b1e48d0.png)

![image](https://user-images.githubusercontent.com/22990858/191202476-1507b562-729a-4a1b-842e-7bd043c9cefc.png)

### Environment

OS :Ubuntu 18.04
TVM:0.9

### Steps to reproduce

I refer to the [example](https://tvm.apache.org/docs/how_to/work_with_relay/using_external_lib.html) to run code.

I get the following error.

```
Traceback (most recent call last):
  File "tvm-cudnn.py", line 53, in <module>
    module.run()
  File "/home/wzy/tvm/python/tvm/contrib/graph_executor.py", line 208, in run
    self._run()
  File "/home/wzy/tvm/python/tvm/_ffi/_ctypes/packed_func.py", line 237, in __call__
    raise get_last_ffi_error()
tvm._ffi.base.TVMError: Traceback (most recent call last):
  3: TVMFuncCall
  2: tvm::runtime::GraphExecutor::Run()
  1: std::_Function_handler<void (), tvm::runtime::GraphExecutor::CreateTVMOp(tvm::runtime::TVMOpParam const&, std::vector<DLTensor, std::allocator<DLTensor> > const&)::{lambda()#3}>::_M_invoke(std::_Any_data const&)
  0: tvm::runtime::PackedFuncObj::Extractor<tvm::runtime::PackedFuncSubObj<tvm::runtime::WrapPackedFunc(int (*)(TVMValue*, int*, int, TVMValue*, int*, void*), tvm::runtime::ObjectPtr<tvm::runtime::Object> const&)::{lambda(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)#1}> >::Call(tvm::runtime::PackedFuncObj const*, tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)
  7: TVMFuncCall
  6: tvm::runtime::GraphExecutor::Run()
  5: std::_Function_handler<void (), tvm::runtime::GraphExecutor::CreateTVMOp(tvm::runtime::TVMOpParam const&, std::vector<DLTensor, std::allocator<DLTensor> > const&)::{lambda()#3}>::_M_invoke(std::_Any_data const&)
  4: tvm::runtime::PackedFuncObj::Extractor<tvm::runtime::PackedFuncSubObj<tvm::runtime::WrapPackedFunc(int (*)(TVMValue*, int*, int, TVMValue*, int*, void*), tvm::runtime::ObjectPtr<tvm::runtime::Object> const&)::{lambda(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)#1}> >::Call(tvm::runtime::PackedFuncObj const*, tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)
  3: 0x00007f11457864a7
  2: 0x00007f1145786b35
  1: TVMBackendGetFuncFromEnv
  0: tvm::runtime::ModuleNode::GetFuncFromEnv(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
  File "/home/wzy/tvm/src/runtime/module.cc", line 120
  File "/home/wzy/tvm/src/runtime/library_module.cc", line 80
TVMError: 
---------------------------------------------------------------
An error occurred during the execution of TVM.
For more information, please see: https://tvm.apache.org/docs/errors.html
---------------------------------------------------------------

  Check failed: ret == 0 (-1 vs. 0) : TVMError: 
---------------------------------------------------------------
An error occurred during the execution of TVM.
For more information, please see: https://tvm.apache.org/docs/errors.html
---------------------------------------------------------------
  Check failed: (f != nullptr) is false: Cannot find function tvm.contrib.cudnn.conv2d.forward in the imported modules or global registry. If this involves ops from a contrib library like cuDNN, ensure TVM was built with the relevant library.
```

how to solve the problem?

**Comment by masahi** [comment]
It is tested in CI. Please check your installation.
