### ISSUE TITLE
unable to import tvm python[Bug] 

### ISSUE THREAD

**Issue by Mr1006853138** [apache/tvm#12897]
Thanks for participating in the TVM community! We use https://discuss.tvm.ai for any general usage questions and discussions. The issue tracker is used for actionable items such as feature proposals discussion, roadmaps, and bug tracking.  You are always welcomed to post on the forum first :smile_cat:

Issues that are inactive for a period of time may get closed. We adopt this policy so that we won't lose track of actionable issues that may fall at the bottom of the pile. Feel free to reopen a new one if you feel there is an additional problem that needs attention when an old one gets closed.

### Expected behavior

Install tvm

### Actual behavior

I have successfully installed tvm before ,as follows
![image](https://user-images.githubusercontent.com/68811054/192138785-c861621c-e06c-4577-903f-c0993494c1e7.png)

But when I used it today, I suddenly found that I couldn't import tvm, as follows
----------------------------------------------
Python 3.9.13 (main, Aug 25 2022, 23:26:10) 
[GCC 11.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tvm
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ljy/tvm/python/tvm/__init__.py", line 33, in <module>
    from .runtime.object import Object
  File "/home/ljy/tvm/python/tvm/runtime/__init__.py", line 22, in <module>
    from .object_path import ObjectPath, ObjectPathPair
  File "/home/ljy/tvm/python/tvm/runtime/object_path.py", line 42, in <module>
    class ObjectPath(Object):
  File "/home/ljy/tvm/python/tvm/_ffi/registry.py", line 69, in register
    check_call(_LIB.TVMObjectTypeKey2Index(c_str(object_name), ctypes.byref(tidx)))
  File "/home/ljy/tvm/python/tvm/_ffi/base.py", line 348, in check_call
    raise get_last_ffi_error()
tvm._ffi.base.TVMError: Traceback (most recent call last):
  [bt] (2) /home/ljy/Ascend/ascend-toolkit/latest/x86_64-linux/lib64/libtvm.so(TVMObjectTypeKey2Index+0x36) [0x7f1177801b16]
  [bt] (1) /home/ljy/Ascend/ascend-toolkit/latest/x86_64-linux/lib64/libtvm.so(tvm::runtime::Object::TypeKey2Index(std::string const&)+0x3e) [0x7f117780194e]
  [bt] (0) /home/ljy/Ascend/ascend-toolkit/latest/x86_64-linux/lib64/libtvm.so(tvm::runtime::TypeContext::TypeKey2Index(std::string const&)+0x3b7) [0x7f1177803e87]
  File "object.cc", line 157
TVMError: [EB9000] Check failed: it != type_key2index_.end(): Cannot find type ObjectPath. Did you forget to register the node by TVM_REGISTER_NODE_TYPE ?
----------------------------------------------

And I have rebuilt tvm ,but it doesn't work.

### Environment

Any environment details, such as: Operating System, TVM version, etc
Operating System:Ubuntu20.04
GCC:11.2.0
TVM:0.10.dev0 (trying)
llvm:13.0.0

### Steps to reproduce

Preferably a minimal script to cause the issue to occur.

**Comment by Mr1006853138** [comment]
This is a problem due to wrong TVM_LIBRARY_PATH.And I added export the environment variable 
 TVM_LIBRARY_PATH=$TVM_PATH/build.It works now.
