### ISSUE TITLE
[Bug] ImportError: cannot import name 'get_const_float' from partially initialized module 'tvm.topi.utils'

### ISSUE THREAD

**Issue by yuwenjun1988** [apache/tvm#13113]
Expected behavior
No Crash

Actual behavior
Crash Stack
Traceback (most recent call last):
  File "/home/yuwenjun/anaconda3/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/yuwenjun/anaconda3/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/mnt/e/code/tvm/python/tvm/exec/popen_worker.py", line 105, in <module>
    main()
  File "/mnt/e/code/tvm/python/tvm/exec/popen_worker.py", line 77, in main
    fn, args, kwargs, timeout = cloudpickle.loads(reader.read(bytes_size))
  File "/mnt/e/code/tvm/python/tvm/autotvm/task/task.py", line 199, in __setstate__
    self.func = cloudpickle.loads(state["func"])
  File "/mnt/e/code/tvm/python/tvm/topi/__init__.py", line 37, in <module>
    from .transform import *
  File "/mnt/e/code/tvm/python/tvm/topi/transform.py", line 26, in <module>
    from .utils import within_index, make_idx, const_vector
  File "/mnt/e/code/tvm/python/tvm/topi/utils.py", line 25, in <module>
    from tvm import relay, te
  File "/mnt/e/code/tvm/python/tvm/relay/__init__.py", line 29, in <module>
    from . import prelude
  File "/mnt/e/code/tvm/python/tvm/relay/prelude.py", line 21, in <module>
    from tvm.relay.transform import ToANormalFormExpr
  File "/mnt/e/code/tvm/python/tvm/relay/transform/__init__.py", line 22, in <module>
    from . import fake_quantization_to_integer, mixed_precision
  File "/mnt/e/code/tvm/python/tvm/relay/transform/fake_quantization_to_integer.py", line 25, in <module>
    from tvm.relay.qnn.op import canonicalizations
  File "/mnt/e/code/tvm/python/tvm/relay/qnn/__init__.py", line 20, in <module>
    from . import op
  File "/mnt/e/code/tvm/python/tvm/relay/qnn/op/__init__.py", line 21, in <module>
    from .qnn import *
  File "/mnt/e/code/tvm/python/tvm/relay/qnn/op/qnn.py", line 26, in <module>
    from tvm.relay.op.nn.utils import get_pad_tuple2d
  File "/mnt/e/code/tvm/python/tvm/relay/op/__init__.py", line 34, in <module>
    from . import strategy
  File "/mnt/e/code/tvm/python/tvm/relay/op/strategy/__init__.py", line 22, in <module>
    from .generic import *
  File "/mnt/e/code/tvm/python/tvm/relay/op/strategy/generic.py", line 24, in <module>
    from tvm.topi.utils import (
ImportError: cannot import name 'get_const_float' from partially initialized module 'tvm.topi.utils' (most likely due to a circular import) (/mnt/e/code/tvm/python/tvm/topi/utils.py)

Environment
Ubuntu 18.04 TVM 0.11.dev0
Any environment details, such as: Operating System, TVM version, etc

Steps to reproduce
run autotvm_relay_x86.py
https://tvm.apache.org/docs/tutorial/autotvm_relay_x86.html#sphx-glr-download-tutorial-autotvm-relay-x86-py

**Comment by yuwenjun1988** [comment]
https://tvm.apache.org/docs/tutorial/autotvm_relay_x86.html#sphx-glr-download-tutorial-autotvm-relay-x86-py

**Comment by yuwenjun1988** [comment]
use TVM 0.10.0 is ok

**Comment by driazati** [comment]
This is supposed to be fixed by 8d2e887dbb3dc693f58dee00ab9c382c85ca21a4, can you try out a build past that commit?

**Comment by masahi** [comment]
Yes it should be fixed by now.
