### ISSUE TITLE
[ci][flaky test] segfault and `java.net.SocketException: Socket closed` in Java unit tests

### ISSUE THREAD

**Issue by driazati** [apache/tvm#13168]
### Jenkins Link

* https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/PR-13108/3/pipeline#step-1584-log-465

<details>

```
[2022-10-21T01:46:48.705Z] -------------------------------------------------------
[2022-10-21T01:46:48.705Z]  T E S T S
[2022-10-21T01:46:48.705Z] -------------------------------------------------------
[2022-10-21T01:46:48.705Z] Running org.apache.tvm.FunctionTest
[2022-10-21T01:46:48.705Z] Try loading tvm4j from native path.
[2022-10-21T01:46:48.705Z] Try loading tvm4j-linux-x86_64 from native path.
[2022-10-21T01:46:48.705Z] libtvm4j loads successfully.
[2022-10-21T01:46:48.705Z] Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.054 sec
[2022-10-21T01:46:48.705Z] Running org.apache.tvm.rpc.RPCTest
[2022-10-21T01:46:48.962Z] java.net.SocketException: Socket closed
[2022-10-21T01:46:48.962Z] 	at java.net.PlainSocketImpl.socketAccept(Native Method)
[2022-10-21T01:46:48.962Z] 	at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:409)
[2022-10-21T01:46:48.962Z] 	at java.net.ServerSocket.implAccept(ServerSocket.java:560)
[2022-10-21T01:46:48.962Z] 	at java.net.ServerSocket.accept(ServerSocket.java:528)
[2022-10-21T01:46:48.962Z] 	at org.apache.tvm.rpc.StandaloneServerProcessor.run(StandaloneServerProcessor.java:46)
[2022-10-21T01:46:48.962Z] 	at org.apache.tvm.rpc.Server$WorkerThread.run(Server.java:38)
[2022-10-21T01:46:48.962Z] java.net.SocketException: Socket closed
[2022-10-21T01:46:48.962Z] 	at java.net.PlainSocketImpl.socketAccept(Native Method)
[2022-10-21T01:46:48.962Z] 	at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:409)
[2022-10-21T01:46:48.962Z] 	at java.net.ServerSocket.implAccept(ServerSocket.java:560)
[2022-10-21T01:46:48.962Z] Tests run: 3, Failures: 0, Errors: 2, Skipped: 1, Time elapsed: 0.067 sec <<< FAILURE!
[2022-10-21T01:46:48.962Z] 	at java.net.ServerSocket.accept(ServerSocket.java:528)
[2022-10-21T01:46:48.962Z] 	at org.apache.tvm.rpc.StandaloneServerProcessor.run(StandaloneServerProcessor.java:46)
[2022-10-21T01:46:48.962Z] 	at org.apache.tvm.rpc.Server$WorkerThread.run(Server.java:38)
[2022-10-21T01:46:48.962Z] Running org.apache.tvm.contrib.GraphExecutorTest
[2022-10-21T01:46:48.962Z] java.net.SocketException: Socket closed
[2022-10-21T01:46:48.962Z] 	at java.net.PlainSocketImpl.socketAccept(Native Method)
[2022-10-21T01:46:48.962Z] 	at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:409)
[2022-10-21T01:46:48.962Z] 	at java.net.ServerSocket.implAccept(ServerSocket.java:560)
[2022-10-21T01:46:48.962Z] 	at java.net.ServerSocket.accept(ServerSocket.java:528)
[2022-10-21T01:46:48.962Z] 	at org.apache.tvm.rpc.StandaloneServerProcessor.run(StandaloneServerProcessor.java:46)
[2022-10-21T01:46:48.962Z] 	at org.apache.tvm.rpc.Server$WorkerThread.run(Server.java:38)
[2022-10-21T01:46:48.962Z] Tests run: 2, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.012 sec <<< FAILURE!
[2022-10-21T01:46:48.962Z] Running org.apache.tvm.NDArrayTest
[2022-10-21T01:46:48.962Z] Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.005 sec
[2022-10-21T01:46:48.962Z] Running org.apache.tvm.ModuleTest
[2022-10-21T01:46:48.962Z] Tests run: 2, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.003 sec <<< FAILURE!
[2022-10-21T01:46:48.962Z] 
[2022-10-21T01:46:48.962Z] Results :
[2022-10-21T01:46:48.962Z] 
[2022-10-21T01:46:48.962Z] Tests in error: 
[2022-10-21T01:46:48.962Z]   test_addone(org.apache.tvm.rpc.RPCTest)
[2022-10-21T01:46:48.962Z]   test_strcat(org.apache.tvm.rpc.RPCTest)
[2022-10-21T01:46:48.962Z]   test_add_one_remote(org.apache.tvm.contrib.GraphExecutorTest)
[2022-10-21T01:46:48.962Z]   test_load_add_func_cuda(org.apache.tvm.ModuleTest)
[2022-10-21T01:46:48.962Z] 
[2022-10-21T01:46:48.962Z] Tests run: 19, Failures: 0, Errors: 4, Skipped: 1
[2022-10-21T01:46:48.962Z] 
[2022-10-21T01:46:48.962Z] !!!!!!! TVM encountered a Segfault !!!!!!!
[2022-10-21T01:46:48.962Z] Stack trace:
[2022-10-21T01:46:48.962Z]   0: backtrace_handler
[2022-10-21T01:46:48.962Z]         at ../src/runtime/logging.cc:133
[2022-10-21T01:46:48.962Z]   1: 0x00007f9258f69f0f
[2022-10-21T01:46:48.962Z]   2: 0x00007f9257c97320
[2022-10-21T01:46:48.962Z]   3: 0x00007f925823945b
[2022-10-21T01:46:48.962Z]   4: 0x00007f9257d14753
[2022-10-21T01:46:48.962Z]   5: 0x00007f9257d15ee8
[2022-10-21T01:46:48.962Z]   6: 0x00007f9257c58f51
[2022-10-21T01:46:48.962Z]   7: 0x00007f9257d21db7
[2022-10-21T01:46:48.962Z]   8: 0x00007f9257d24707
[2022-10-21T01:46:48.962Z]   9: 0x00007f9258392142
[2022-10-21T01:46:48.962Z]   10: 0x00007f925839241c
[2022-10-21T01:46:48.962Z]   11: 0x00007f9258218921
[2022-10-21T01:46:48.962Z]   12: start_thread
[2022-10-21T01:46:48.962Z]   13: __clone
[2022-10-21T01:46:48.962Z]   14: 0xffffffffffffffff
[2022-10-21T01:46:48.962Z] 
[2022-10-21T01:46:48.962Z] Segmentation fault
[2022-10-21T01:46:48.962Z] [[1;34mINFO[m] [1m------------------------------------------------------------------------[m
[2022-10-21T01:46:48.962Z] [[1;34mINFO[m] [1mReactor Summary for TVM4J Package - Parent 0.0.1-SNAPSHOT:[m
[2022-10-21T01:46:48.962Z] [[1;34mINFO[m] 
[2022-10-21T01:46:48.962Z] [[1;34mINFO[m] TVM4J Package - Parent ............................. [1;32mSUCCESS[m [  1.008 s]
[2022-10-21T01:46:48.962Z] [[1;34mINFO[m] TVM4J Package - Core ............................... [1;31mFAILURE[m [  4.247 s]
[2022-10-21T01:46:48.962Z] [[1;34mINFO[m] TVM4J Package - Native Parent ...................... [1;33mSKIPPED[m
[2022-10-21T01:46:48.962Z] [[1;34mINFO[m] TVM4J Package - Native Linux-x86_64 ................ [1;33mSKIPPED[m
[2022-10-21T01:46:48.962Z] [[1;34mINFO[m] TVM4J Package - Full Parent ........................ [1;33mSKIPPED[m
[2022-10-21T01:46:48.962Z] [[1;34mINFO[m] TVM4J Package - Full Linux-x86_64 .................. [1;33mSKIPPED[m
[2022-10-21T01:46:48.962Z] [[1;34mINFO[m] [1m------------------------------------------------------------------------[m
[2022-10-21T01:46:48.962Z] [[1;34mINFO[m] [1;31mBUILD FAILURE[m
[2022-10-21T01:46:48.962Z] [[1;34mINFO[m] [1m------------------------------------------------------------------------[m
[2022-10-21T01:46:48.962Z] [[1;34mINFO[m] Total time:  5.666 s
[2022-10-21T01:46:48.962Z] [[1;34mINFO[m] Finished at: 2022-10-21T01:46:48Z
[2022-10-21T01:46:48.962Z] [[1;34mINFO[m] [1m------------------------------------------------------------------------[m
[2022-10-21T01:46:48.962Z] [[1;31mERROR[m] Failed to execute goal [32morg.apache.maven.plugins:maven-surefire-plugin:2.7:test[m [1m(default-test)[m on project [36mtvm4j-core[m: [1;31mThere are test failures.[m
[2022-10-21T01:46:48.962Z] [[1;31mERROR[m] [1;31m[m
[2022-10-21T01:46:48.962Z] [[1;31mERROR[m] [1;31mPlease refer to /workspace/jvm/core/target/surefire-reports for the individual test results.[m
[2022-10-21T01:46:48.962Z] [[1;31mERROR[m] -> [1m[Help 1][m
[2022-10-21T01:46:48.962Z] [[1;31mERROR[m] 
[2022-10-21T01:46:48.962Z] [[1;31mERROR[m] To see the full stack trace of the errors, re-run Maven with the [1m-e[m switch.
[2022-10-21T01:46:48.962Z] [[1;31mERROR[m] Re-run Maven using the [1m-X[m switch to enable full debug logging.
[2022-10-21T01:46:48.962Z] [[1;31mERROR[m] 
[2022-10-21T01:46:48.962Z] [[1;31mERROR[m] For more information about the errors and possible solutions, please read the following articles:
[2022-10-21T01:46:48.962Z] [[1;31mERROR[m] [1m[Help 1][m http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[2022-10-21T01:46:48.962Z] [[1;31mERROR[m] 
[2022-10-21T01:46:48.962Z] [[1;31mERROR[m] After correcting the problems, you can resume the build with the command
[2022-10-21T01:46:48.962Z] [[1;31mERROR[m]   [1mmvn <goals> -rf :tvm4j-core[m
[2022-10-21T01:46:48.962Z] Makefile:165: recipe for target 'jvmpkg' failed
[2022-10-21T01:46:48.962Z] make: *** [jvmpkg] Error 1
```

</details>

### Flakiness

This has shown up a few times before as well on other branches

cc @Mousius @areusch @gigiblender

**Comment by driazati** [comment]
cc @yzhliu any ideas on this failure?
