### ISSUE TITLE
[docs] Some tutorials are missing

### ISSUE THREAD

**Issue by driazati** [apache/tvm#13766]
Some tutorials that are defined in `gallery/` are not included in the final built website since their enclosing folders are not listed in `docs/conf.py`, for example the `work_with_pytorch` tutorials https://github.com/apache/tvm/tree/main/gallery/how_to/work_with_pytorch do not appear on this list https://tvm.apache.org/docs/how_to/index.html

These may need some attention from the authors since (at least the PyTorch tutorials) they don't run in CI and just adding them to the list hits other errors:

<details>

```
[2023-01-11T22:10:49.638Z] Unexpected failing examples:
[2023-01-11T22:10:49.638Z] /workspace/gallery/how_to/work_with_pytorch/using_as_torch.py failed leaving traceback:
[2023-01-11T22:10:49.638Z] Traceback (most recent call last):
[2023-01-11T22:10:49.638Z]   File "/workspace/gallery/how_to/work_with_pytorch/using_as_torch.py", line 111, in <module>
[2023-01-11T22:10:49.638Z]     tvm_depthwise.tune()
[2023-01-11T22:10:49.638Z]   File "/workspace/python/tvm/contrib/torch/as_torch.py", line 108, in tune
[2023-01-11T22:10:49.638Z]     self.build(target)
[2023-01-11T22:10:49.638Z]   File "/workspace/python/tvm/contrib/torch/as_torch.py", line 118, in build
[2023-01-11T22:10:49.638Z]     raise ValueError('as_torch requires the flag /"USE_PT_TVMDSOOP/" set in config.cmake')
[2023-01-11T22:10:49.638Z] ValueError: as_torch requires the flag /"USE_PT_TVMDSOOP/" set in config.cmake
[2023-01-11T22:10:49.638Z] 
[2023-01-11T22:10:49.638Z] 
[2023-01-11T22:10:49.638Z] /workspace/gallery/how_to/work_with_pytorch/using_optimized_torch.py failed leaving traceback:
[2023-01-11T22:10:49.638Z] Traceback (most recent call last):
[2023-01-11T22:10:49.638Z]   File "/workspace/gallery/how_to/work_with_pytorch/using_optimized_torch.py", line 48, in <module>
[2023-01-11T22:10:49.638Z]     from tvm.meta_schedule import TuneConfig
[2023-01-11T22:10:49.638Z] ImportError: cannot import name 'TuneConfig' from 'tvm.meta_schedule' (/workspace/python/tvm/meta_schedule/__init__.py)
```

</details>

**Comment by cchung100m** [comment]
Hi @driazati 

it been a while since you noticed this issue and I'd like to help if the problem still existed.

May I know your suggestions to fix this issue if that is convenient?
