### ISSUE TITLE
ValueError: Cannot find global function relay.backend.contrib.uma.RegisterTarget [Bug] 

### ISSUE THREAD

**Issue by leoluopy** [apache/tvm#14055]
now , i am going to add a new backend for tvm . 
first of all , i need to make uma pure c backend workable . 
after building tvm from souce , and i run the command below:
python tvm/apps/uma/vanilla_accelerator/run.py

errors occur:

Traceback (most recent call last):
  File "/home/algo_share/projects/peiyuanluo/workspace/tvm/apps/uma/vanilla_accelerator/run.py", line 82, in <module>
    main()
  File "/home/algo_share/projects/peiyuanluo/workspace/tvm/apps/uma/vanilla_accelerator/run.py", line 65, in main
    uma_backend.register()
  File "/home/algo_share/projects/peiyuanluo/workspace/tvm/python/tvm/relay/backend/contrib/uma/backend.py", line 279, in register
    registration_func = tvm.get_global_func("relay.backend.contrib.uma.RegisterTarget")
  File "/home/algo_share/projects/peiyuanluo/workspace/tvm/python/tvm/_ffi/registry.py", line 234, in get_global_func
    return _get_global_func(name, allow_missing)
  File "/home/algo_share/projects/peiyuanluo/workspace/tvm/python/tvm/_ffi/_ctypes/packed_func.py", line 294, in _get_global_func
    raise ValueError("Cannot find global function %s" % name)
ValueError: Cannot find global function relay.backend.contrib.uma.RegisterTarget

do any one have some idea ?

**Comment by shoskensMagics** [comment]
Setup `set(USE_UMA ON)` in your `config.cmake`.

**Comment by leoluopy** [comment]
@shoskensMagics
it works , thanks.
