### ISSUE TITLE
[Bug] AttributeError: Module has no function 'get_input_name'

### ISSUE THREAD

**Issue by leoluopy** [apache/tvm#14098]
hi ,
   i am runing the script here to generate micro tvm crt project from pytorch model:
https://tvm.apache.org/docs/how_to/work_with_microtvm/micro_pytorch.html#sphx-glr-how-to-work-with-microtvm-micro-pytorch-py

   while it comes to :
aot_executor = tvm.runtime.executor.aot_executor.AotModule(session.create_aot_executor())

some thing went wrong. the log is at below:
[11:35:08] /home/leo/tvm/src/runtime/micro/micro_session.cc:377: remote: DumpMetadata:
[11:35:08] /home/leo/tvm/src/runtime/micro/micro_session.cc:377: remote: 	mod_name=tvmgen_default
[11:35:08] /home/leo/tvm/src/runtime/micro/micro_session.cc:377: remote: 	version=1
[11:35:08] /home/leo/tvm/src/runtime/micro/micro_session.cc:377: remote: 	num_inputs=1
[11:35:08] /home/leo/tvm/src/runtime/micro/micro_session.cc:377: remote: 	num_outputs=1
[11:35:08] /home/leo/tvm/src/runtime/micro/micro_session.cc:377: remote: 	num_workspace_pools=0
[11:35:08] /home/leo/tvm/src/runtime/micro/micro_session.cc:377: remote: 	num_constant_pools=0
[11:35:08] /home/leo/tvm/src/runtime/micro/micro_session.cc:377: remote: 	input[0]: input0
[11:35:08] /home/leo/tvm/src/runtime/micro/micro_session.cc:377: remote: 	output[0]: output0
[11:35:08] /home/leo/tvm/src/runtime/micro/micro_session.cc:377: remote: input allocate[0]: input0
[11:35:08] /home/leo/tvm/src/runtime/micro/micro_session.cc:377: remote: output allocate[0]: output0
Traceback (most recent call last):
  File "/home/leo/tvm/expworkspace/torch2micro_tvm.py", line 124, in <module>
    aot_executor = tvm.runtime.executor.aot_executor.AotModule(session.create_aot_executor())
  File "/home/leo/tvm/python/tvm/runtime/executor/aot_executor.py", line 70, in __init__
    self._get_input_name = module["get_input_name"]
  File "/home/leo/tvm/python/tvm/runtime/module.py", line 191, in __getitem__
    return self.get_function(name)
  File "/home/leo/tvm/python/tvm/runtime/module.py", line 175, in get_function
    raise AttributeError("Module has no function '%s'" % name)
AttributeError: Module has no function 'get_input_name'

do anyone have some idea ?

**Comment by masahi** [comment]
Do you have the commit https://github.com/apache/tvm/pull/14071?

**Comment by leoluopy** [comment]
@masahi  no , thanks , i am going to pull it right now. and rebuilt it then try again .

**Comment by leoluopy** [comment]
@masahi , now the project works fine . and i have another question .
the script [sphx-glr-how-to-work-with-microtvm-micro-pytorch-py] generate a cmake project . 
are all the sources auto-generated ?  or just some sources [default_lib0.cc , default_lib1.cc , default_lib2.cc]  are generated then runtime and main.cc are handwritten .

**Comment by masahi** [comment]
Please ask a question in the discussion forum.

**Comment by leoluopy** [comment]
@masahi , 
   thanks , i walk through the generated code and tvm main repo code , and get the result .
