### ISSUE TITLE
[Bug] parse the output number of MaxPool incorrectly

### ISSUE THREAD

**Issue by jikechao** [apache/tvm#14614]
For the following ONNX model, ONNXConverter will mistakenly parse the output number and thus triggered an assertion failure.

### The ONNX structure:

![image](https://user-images.githubusercontent.com/29506758/231821580-970f2abf-22cf-4aba-861f-0fc7ca4b033d.png)
You can download the model by this link:  https://github.com/jikechao/onnx_models/blob/main/model.onnx

### Crash message:
```
Traceback (most recent call last):    
...
    irmod, params = relay.frontend.from_onnx(predict_model, shape_dict, freeze_params=True)
  File "/workplace/software/tvm/tvm/python/tvm/relay/frontend/onnx.py", line 7346, in from_onnx
    mod, params = g.from_onnx(graph, opset)
  File "/workplace/software/tvm/tvm/python/tvm/relay/frontend/onnx.py", line 6963, in from_onnx
    self._construct_nodes(graph)
  File "/workplace/software/tvm/tvm/python/tvm/relay/frontend/onnx.py", line 7120, in _construct_nodes
    len(node_output), outputs_num, op_name
AssertionError: Number of output mismatch 2 vs 1 in MaxPool.
```

### reproducible script:
```
import onnx
from tvm import relay

onnx_model_path = "model.onnx"
model = onnx.load(onnx_model_path)
irmod, params = relay.frontend.from_onnx(model, {'x': (1, 1, 5, 5)}, freeze_params=True)
```

**Comment by jikechao** [comment]
@masahi @jwfromm @vvchernov Could you help me check this crash? Thanks a lot!

**Comment by vvchernov** [comment]
Hello @jikechao! It is simply not supported on ONNX front-end of TVM. The implementation of MaxPool (AveragePool as well) was done for onnx opset = 1, but optional second output (Indices) appeared only since opset = 8. It needs to extend implementation for the op, if you do it, it will be good

**Comment by jikechao** [comment]
@vvchernov Thanks for your comments! Indeed, This crash was caused by Indices appearing since opset=8. However, this feature existing more than 5 years. Thus, Supporting Indices to avoid this crash may not be trivial. Thus, I'll try to fix it.

**Comment by vvchernov** [comment]
Hello @jikechao! Some nits may be help you to fix. There can be problems with optional output and indices calculation, in both cases you can see how it was implemented for scatter_elements (ScatterElements class)
