### ISSUE TITLE
[Bug] tvmc --help error

### ISSUE THREAD

**Issue by YaoJiawei329** [apache/tvm#14633]
Hi, I successfully installed tvm, got tvm.dll and tvm_runtime.dll under tvm/build/Release. However, after 
python setup.py install
in a conda env, I can successfully import tvm, but 
tvmc --help
falied.

### Actual behavior

(torch182) C:\Users\dlyjw>tvmc --help
Traceback (most recent call last):
  File "C:\Users\dlyjw\.conda\envs\torch182\Scripts\tvmc-script.py", line 33, in <module>
    sys.exit(load_entry_point('tvm==0.13.dev40+g62f9b1d29', 'console_scripts', 'tvmc')())
  File "C:\Users\dlyjw\.conda\envs\torch182\lib\site-packages\tvm-0.13.dev40+g62f9b1d29-py3.8-win-amd64.egg\tvm\driver\tvmc\main.py", line 118, in main
    sys.exit(_main(sys.argv[1:]))
  File "C:\Users\dlyjw\.conda\envs\torch182\lib\site-packages\tvm-0.13.dev40+g62f9b1d29-py3.8-win-amd64.egg\tvm\driver\tvmc\main.py", line 74, in _main
    json_param_dict = read_and_convert_json_into_dict(config_arg)
  File "C:\Users\dlyjw\.conda\envs\torch182\lib\site-packages\tvm-0.13.dev40+g62f9b1d29-py3.8-win-amd64.egg\tvm\driver\tvmc\config_options.py", line 119, in read_and_convert_json_into_dict
    config_dir = get_configs_json_dir()
  File "C:\Users\dlyjw\.conda\envs\torch182\lib\site-packages\tvm-0.13.dev40+g62f9b1d29-py3.8-win-amd64.egg\tvm\driver\tvmc\config_options.py", line 69, in get_configs_json_dir
    raise ConfigsJsonNotFoundError()
tvm.driver.tvmc.config_options.ConfigsJsonNotFoundError

### Environment

Windows11, TVM=0.13, conda env with python=3.8

### Steps to reproduce

tvmc --help

**Comment by YaoJiawei329** [comment]
Oh, I have solved the bug.

**Comment by jsjs0827** [comment]
How to solve?
