### ISSUE TITLE
[Bug] Relay type checker is unable to show types match about Relay.any()

### ISSUE THREAD

**Issue by jikechao** [apache/tvm#14648]
The test case will crash at the latest version of TVM. It throws the error:   <**The Relay type checker is unable to show the following types match:  Tensor[(16, meta[tir.FloorDiv][0], 3, 3), float32]**> 
```
import tvm
from tvm import relay
import numpy as np
from tvm.relay import transform

data = relay.var(
    "data", shape=(relay.Any(), relay.Any(), relay.Any(), relay.Any()), dtype="float32"
)
weigth = relay.const(np.full((16, 16, 3, 3), 0.25), dtype="float32")
x = relay.nn.conv2d(data, weigth, kernel_size=(3, 3), channels=16, groups=2)
mod = tvm.IRModule.from_expr(x)
mod = transform.InferType()(mod)
```

### The crash message:
```
The Relay type checker is unable to show the following types match:
  Tensor[(16, meta[tir.FloorDiv][0], 3, 3), float32]

  Tensor[(16, 16, 3, 3), float32]
In particular:
  dimension 1 conflicts: T.Any() // 2 does not match 16.
The Relay type checker is unable to show the following types match.
In particular `Tensor[(16, 16, 3, 3), float32]` does not match `Tensor[(16, meta[tir.FloorDiv][0], 3, 3), float32]
`
Traceback (most recent call last):
  File "b.py", line 13, in <module>
    mod = transform.InferType()(mod)
  File "/workplace/software/tvm/tvm/python/tvm/ir/transform.py", line 160, in __call__
    return _ffi_transform_api.RunPass(self, mod)
  File "/workplace/software/tvm/tvm/python/tvm/_ffi/_ctypes/packed_func.py", line 237, in __call__
    raise get_last_ffi_error()
tvm.error.DiagnosticError: Traceback (most recent call last):
  7: TVMFuncCall
  6: tvm::runtime::PackedFuncObj::Extractor<tvm::runtime::PackedFuncSubObj<tvm::runtime::TypedPackedFunc<tvm::IRModule (tvm::transform::Pass, tvm::IRModule)>::AssignTypedLambda<tvm::transform::$_6>(tvm::transform::$_6, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)::{lambda(tvm::runtime::TVMArgs const&, tvm::runtime::TVMRetValue*)#1}> >::Call(tvm::runtime::PackedFuncObj const*, tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)
  5: tvm::transform::Pass::operator()(tvm::IRModule) const
  4: tvm::transform::Pass::operator()(tvm::IRModule, tvm::transform::PassContext const&) const
  3: tvm::transform::ModulePassNode::operator()(tvm::IRModule, tvm::transform::PassContext const&) const
  2: tvm::runtime::PackedFuncObj::Extractor<tvm::runtime::PackedFuncSubObj<tvm::runtime::TypedPackedFunc<tvm::IRModule (tvm::IRModule, tvm::transform::PassContext)>::AssignTypedLambda<tvm::relay::transform::InferType()::$_2>(tvm::relay::transform::InferType()::$_2)::{lambda(tvm::runtime::TVMArgs const&, tvm::runtime::TVMRetValue*)#1}> >::Call(tvm::runtime::PackedFuncObj const*, tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)
  1: tvm::DiagnosticContext::Render()
  0: _ZN3tvm7runtime6detail
  File "/workplace/software/tvm/tvm/src/ir/diagnostic.cc", line 131
DiagnosticError: one or more error diagnostics were emitted, please check diagnostic render for output.
```

@shengxinhu Could you take a look?

**Comment by shengxinhu** [comment]
@jikechao  I could not reproduce such issue. I am wonder that If test case failed, it should not be able to pass jenkins test to merge into main branch.

**Comment by jikechao** [comment]
Hi @shengxinhu, your analysis is totally correct! I update the `llvm-clang-8.0` to `llvm-clang-12.0` and rebuild TVM. The test case can pass in the new 
 environment. Thus, I guess this crash is related to the version of `llvm-clang`.
