### ISSUE TITLE
[Bug] [Unity] [TIR] There is no definition of I.GlobalVar("resize2d")

### ISSUE THREAD

**Issue by Civitasv** [apache/tvm#15306]
I'm using the `relax.build` function to build my IR module.

The IR module contains a line:

```txt
lv254 = R.call_tir(resize2d, (lv253,), out_sinfo=R.Tensor((1, 512, 128, 128), dtype="float32"))
```

### Expected behavior

It should build successfully.

### Actual behavior

Errors as follow:

```txt
File "/home/xxx/xxx/tvm/python/tvm/relax/vm_build.py", line 321, in build
    new_mod = seq(mod)
  File "/home/xxx/xxx/tvm/python/tvm/ir/transform.py", line 238, in __call__
    return _ffi_transform_api.RunPass(self, mod)
  File "/home/xxx/xxx/tvm/python/tvm/_ffi/_ctypes/packed_func.py", line 238, in __call__
    raise get_last_ffi_error()
tvm.error.InternalError: Traceback (most recent call last):
  26: TVMFuncCall
  25: tvm::runtime::PackedFuncObj::Extractor<tvm::runtime::PackedFuncSubObj<tvm::runtime::TypedPackedFunc<tvm::IRModule (tvm::transform::Pass, tvm::IRModule)>::AssignTypedLambda<tvm::transform::__mk_TVM9::{lambda(tvm::transform::Pass, tvm::IRModule)#1}>(tvm::transform::__mk_TVM9::{lambda(tvm::transform::Pass, tvm::IRModule)#1}, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)::{lambda(tvm::runtime::TVMArgs const&, tvm::runtime::TVMRetValue*)#1}> >::Call(tvm::runtime::PackedFuncObj const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, tvm::runtime::TVMRetValue)
  24: tvm::transform::Pass::operator()(tvm::IRModule) const
  23: tvm::transform::Pass::operator()(tvm::IRModule, tvm::transform::PassContext const&) const
  22: tvm::transform::SequentialNode::operator()(tvm::IRModule, tvm::transform::PassContext const&) const
  21: tvm::transform::Pass::operator()(tvm::IRModule, tvm::transform::PassContext const&) const
  20: tvm::relax::transform::FunctionPassNode::operator()(tvm::IRModule, tvm::transform::PassContext const&) const
  19: _ZN3tvm7runtime13PackedFuncObj
  18: tvm::runtime::TypedPackedFunc<tvm::relax::Function (tvm::relax::Function, tvm::IRModule, tvm::transform::PassContext)>::AssignTypedLambda<tvm::relax::transform::RewriteDataflowReshape()::{lambda(tvm::relax::Function, tvm::IRModule, tvm::transform::PassContext)#1}>(tvm::relax::transform::RewriteDataflowReshape()::{lambda(tvm::relax::Function, tvm::IRModule, tvm::transform::PassContext)#1})::{lambda(tvm::runtime::TVMArgs const&, tvm::runtime::TVMRetValue*)#1}::operator()(tvm::runtime::TVMArgs const&, tvm::runtime::TVMRetValue*) const
  17: tvm::relax::RewriteDataflowReshape(tvm::relax::Function const&, tvm::IRModule const&)
  16: tvm::relax::ExprMutator::VisitExpr(tvm::RelayExpr const&)
  15: tvm::relax::ExprFunctor<tvm::RelayExpr (tvm::RelayExpr const&)>::VisitExpr(tvm::RelayExpr const&)
  14: _ZZN3tvm5relax11ExprFunctorIFNS_9RelayExprERKS2_EE10InitVTableEvENUlRKNS_
  13: tvm::relax::ExprMutator::VisitExpr_(tvm::relax::FunctionNode const*)
  12: tvm::relax::ExprMutator::VisitWithNewScope(tvm::RelayExpr const&, tvm::runtime::Optional<tvm::runtime::Array<tvm::relax::Var, void> >)
  11: tvm::relax::ExprMutator::VisitExpr(tvm::RelayExpr const&)
  10: tvm::relax::ExprFunctor<tvm::RelayExpr (tvm::RelayExpr const&)>::VisitExpr(tvm::RelayExpr const&)
  9: _ZZN3tvm5relax11ExprFunctorIFNS_9RelayExprERKS2_EE10InitVTableEvENUlRKNS_
  8: tvm::relax::ExprMutator::VisitExpr_(tvm::relax::SeqExprNode const*)
  7: tvm::relax::DataflowReshapeRewriter::VisitBindingBlock(tvm::relax::BindingBlock const&)
  6: tvm::relax::ExprMutator::VisitBindingBlock_(tvm::relax::DataflowBlockNode const*)
  5: tvm::relax::ExprMutator::VisitBinding_(tvm::relax::VarBindingNode const*, tvm::relax::PrimValueNode const*)
  4: tvm::relax::ExprMutator::VisitExpr(tvm::RelayExpr const&)
  3: tvm::relax::ExprFunctor<tvm::RelayExpr (tvm::RelayExpr const&)>::VisitExpr(tvm::RelayExpr const&)
  2: _ZZN3tvm5relax11ExprFunctorIFNS_9RelayExprERKS2_EE10InitVTableEvENUlRKNS_
  1: tvm::relax::DataflowReshapeRewriter::VisitExpr_(tvm::relax::CallNode const*)
  0: tvm::IRModuleNode::Lookup(tvm::GlobalVar const&) const
  File "/home/xxx/xxx/tvm/src/ir/module.cc", line 288
InternalError: Check failed: (it != functions.end()) is false: There is no definition of I.GlobalVar("resize2d")
```

### Environment

OS: Ubuntu 20.04
TVM: almost latest version of unity branch

### Triage

* needs-triage

cc @Hzfengsy @junrushao @quic-sanirudh @shingjan

**Comment by Hzfengsy** [comment]
Could you please confirm if PrimFunc `resize2d` is in the IRModule?

**Comment by Civitasv** [comment]
It’s not in the tvm script. Only call_tir function exists. And to make context clear, this ir module is translated from onnx. So maybe it’s also related to the onnx frontend.

**Comment by Hzfengsy** [comment]
Try to print the IRModule out and check :)

**Comment by Civitasv** [comment]
Okay, here's the IRModule:

```py
# from tvm.script import ir as I
# from tvm.script import relax as R

@I.ir_module
class Module:
    @R.function
    def main(latent_sample: R.Tensor((1, 4, 64, 64), dtype="float32")) -> R.Tensor((1, 3, 512, 512), dtype="float32"):
        R.func_attr({"num_input": 1})
        with R.dataflow():
            ...
            lv254 = R.call_tir(resize2d, (lv253,), out_sinfo=R.Tensor((1, 512, 128, 128), dtype="float32"))
            ...
            lv378 = R.call_tir(resize2d1, (lv377,), out_sinfo=R.Tensor((1, 512, 256, 256), dtype="float32"))
            ...
            lv505 = R.call_tir(resize2d2, (lv504,), out_sinfo=R.Tensor((1, 256, 512, 512), dtype="float32"))
            ...
            gv: R.Tensor((1, 3, 512, 512), dtype="float32") = R.add(lv648, lv649)
            R.output(gv)
        return gv

# Metadata omitted. Use show_meta=True in script() method to show it.
```

**Comment by Civitasv** [comment]
It seems unusual that there is no `@T.prim_func` function available.

**Comment by MasterJH5574** [comment]
Interesting. So it is expected to have
```python
@T.prim_func
def resize2d(....):
  ...
```
in the IRModule. Given that there is such CallTIR `R.call_tir(resize2d, ...)`, I suppose `resize2d` must exist in the IRModule at some time point before `relax.build`, and was then accidentally dropped. It might be helpful to go through the passes you used and check when `resize2d` exists and disappeared.

**Comment by Civitasv** [comment]
Sorry, turns out it's my misuse when I rename the function name at runtime. Anyway, much appreciate for your help!
