### ISSUE TITLE
[Bug] [Unity] [Frontend] [ONNX] Gather: ValueError: Need to fix this case.

### ISSUE THREAD

**Issue by Civitasv** [apache/tvm#15316]
Here's part of my ONNX model:

![image](https://github.com/apache/tvm/assets/37768049/a247df0b-e135-4f58-91dd-d47a2106ae01)

One of the input to Gather op has type of `relax.ShapeExpr`.

### Expected behavior

It should be imported successfully.

### Actual behavior

Errors as follow:

```txt
Traceback (most recent call last):
    ir_mod = from_onnx(model, shape_dict=input_shape_dict, **attrs)
  File "/home/xxx/xxx/tvm/python/tvm/relax/frontend/onnx/onnx_frontend.py", line 2191, in from_onnx
    return g.from_onnx(graph, opset)
  File "/home/xxx/xxx/tvm/python/tvm/relax/frontend/onnx/onnx_frontend.py", line 1850, in from_onnx
    self._construct_nodes(graph)
  File "/home/xxx/xxx/tvm/python/tvm/relax/frontend/onnx/onnx_frontend.py", line 2001, in _construct_nodes
    op = self._convert_operator(op_name, inputs, attr, self.opset)
  File "/home/xxx/xxx/tvm/python/tvm/relax/frontend/onnx/onnx_frontend.py", line 2097, in _convert_operator
    sym = op_function(self.bb, inputs, attrs, [self._nodes, self._params])
  File "/home/xxx/xxx/tvm/python/tvm/relax/frontend/onnx/onnx_frontend.py", line 358, in _impl_v13
    raise ValueError("Need to fix this case.")
ValueError: Need to fix this case.
[15:55:15] /home/xxx/xxx/tvm/src/relax/ir/block_builder.cc:64: Warning: BlockBuilder destroyed with remaining blocks!
```

### Environment

OS: Ubuntu 20.04
TVM: almost latest version of unity branch

### Triage

* needs-triage

cc @KJlaccHoeUM9l @quic-sanirudh

**Comment by Civitasv** [comment]
Sorry, it's not because onnx frontend, the reason is I have a mistake on input shape dict.
