### ISSUE TITLE
[Bug] Can't import tvm.tir.tensor_intrin

### ISSUE THREAD

**Issue by twmht** [apache/tvm#15411]
Thanks for participating in the TVM community! We use https://discuss.tvm.ai for any general usage questions and discussions. The issue tracker is used for actionable items such as feature proposals discussion, roadmaps, and bug tracking.  You are always welcomed to post on the forum first :smile_cat:

Issues that are inactive for a period of time may get closed. We adopt this policy so that we won't lose track of actionable issues that may fall at the bottom of the pile. Feel free to reopen a new one if you feel there is an additional problem that needs attention when an old one gets closed.

### Expected behavior

```
import tvm.tir.tensor_intrin
```

### Actual behavior

```
error: unsupported operand type(s) for +: 'NoneType' and 'int'
 --> /home/acer/tvm/python/tvm/tir/tensor_intrin/rocm.py:337:13
     |  
 337 |              C[tx, 0:local_size_out] = T.call_llvm_pure_intrin(
     |                                                                
Traceback (most recent call last):
  File "/home/acer/tvm/python/tvm/script/parser/core/parser.py", line 204, in _wrapper
    return func(self, node)
  File "/home/acer/tvm/python/tvm/script/parser/tir/parser.py", line 254, in visit_assign
    rhs = self.eval_expr(node.value)
  File "/home/acer/tvm/python/tvm/script/parser/core/parser.py", line 329, in eval_expr
    return eval_expr(self, node, var_values)
  File "/home/acer/tvm/python/tvm/script/parser/core/evaluator.py", line 412, in eval_expr
    return ExprEvaluator.eval(parser, value_table, node)
  File "/home/acer/tvm/python/tvm/script/parser/core/evaluator.py", line 107, in eval
    result = self._visit(node)  # pylint: disable=protected-access
  File "/home/acer/tvm/python/tvm/script/parser/core/evaluator.py", line 195, in _visit
    s.upper.end_col_offset + 1,
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test_meta_scheduler.py", line 2, in <module>
    import tvm.tir.tensor_intrin
  File "/home/acer/tvm/python/tvm/tir/tensor_intrin/__init__.py", line 19, in <module>
    from . import arm_cpu, cuda, rocm, x86, hexagon
  File "/home/acer/tvm/python/tvm/tir/tensor_intrin/rocm.py", line 463, in <module>
    TensorIntrin.register(ROCM_MFMA_f32f32f32_INTRIN, *get_mfma_intrin(4, "float32", "float32"))
  File "/home/acer/tvm/python/tvm/tir/tensor_intrin/rocm.py", line 323, in get_mfma_intrin
    def mfma_sync_impl_float(a: T.handle, b: T.handle, c: T.handle) -> None:
  File "/home/acer/tvm/python/tvm/script/parser/tir/entry.py", line 68, in prim_func
    return decorator_wrapper(func)
  File "/home/acer/tvm/python/tvm/script/parser/tir/entry.py", line 62, in decorator_wrapper
    f = parse(func, utils.inspect_function_capture(func))
  File "/home/acer/tvm/python/tvm/script/parser/core/entry.py", line 78, in parse
    parser.parse(extra_vars=extra_vars)
  File "/home/acer/tvm/python/tvm/script/parser/core/parser.py", line 272, in parse
    self.visit(node)
  File "/home/acer/tvm/python/tvm/script/parser/core/parser.py", line 447, in visit
    func(node)
  File "/home/acer/tvm/python/tvm/script/parser/core/doc.py", line 257, in generic_visit
    self.visit(value)
  File "/home/acer/tvm/python/tvm/script/parser/core/parser.py", line 435, in visit
    self.visit(item)
  File "/home/acer/tvm/python/tvm/script/parser/core/parser.py", line 447, in visit
    func(node)
  File "/home/acer/tvm/python/tvm/script/parser/core/parser.py", line 505, in visit_FunctionDef
    _dispatch_wrapper(func)(self, node)
  File "/home/acer/tvm/python/tvm/script/parser/core/parser.py", line 204, in _wrapper
    return func(self, node)
  File "/home/acer/tvm/python/tvm/script/parser/tir/parser.py", line 415, in visit_function_def
    self.visit_body(node.body)
  File "/home/acer/tvm/python/tvm/script/parser/core/parser.py", line 468, in visit_body
    self.visit(stmt)
  File "/home/acer/tvm/python/tvm/script/parser/core/parser.py", line 447, in visit
    func(node)
  File "/home/acer/tvm/python/tvm/script/parser/core/parser.py", line 589, in visit_With
    return _dispatch(self, "With")(self, node)
  File "/home/acer/tvm/python/tvm/script/parser/core/parser.py", line 204, in _wrapper
    return func(self, node)
  File "/home/acer/tvm/python/tvm/script/parser/tir/parser.py", line 366, in visit_with
    self.visit_body(node.body)
  File "/home/acer/tvm/python/tvm/script/parser/core/parser.py", line 468, in visit_body
    self.visit(stmt)
  File "/home/acer/tvm/python/tvm/script/parser/core/parser.py", line 447, in visit
    func(node)
  File "/home/acer/tvm/python/tvm/script/parser/core/parser.py", line 604, in visit_Assign
    return _dispatch(self, "Assign")(self, node)
  File "/home/acer/tvm/python/tvm/script/parser/core/parser.py", line 208, in _wrapper
    self.report_error(node, e)
  File "/home/acer/tvm/python/tvm/script/parser/core/parser.py", line 418, in report_error
    self.diag.error(node, msg)
  File "/home/acer/tvm/python/tvm/script/parser/core/diagnostics.py", line 257, in error
    self.ctx.render()
  File "/home/acer/tvm/python/tvm/ir/diagnostics/__init__.py", line 119, in render
    _ffi_api.DiagnosticContextRender(self)
  File "tvm/_ffi/_cython/./packed_func.pxi", line 331, in tvm._ffi._cy3.core.PackedFuncBase.__call__
  File "tvm/_ffi/_cython/./packed_func.pxi", line 262, in tvm._ffi._cy3.core.FuncCall
  File "tvm/_ffi/_cython/./packed_func.pxi", line 251, in tvm._ffi._cy3.core.FuncCall3
  File "tvm/_ffi/_cython/./base.pxi", line 181, in tvm._ffi._cy3.core.CHECK_CALL
tvm.error.DiagnosticError: Traceback (most recent call last):
  2: TVMFuncCall
  1: tvm::runtime::PackedFuncObj::Extractor<tvm::runtime::PackedFuncSubObj<tvm::runtime::TypedPackedFunc<void (tvm::DiagnosticContext)>::AssignTypedLambda<tvm::__mk_TVM11::{lambda(tvm::DiagnosticContext)#1}>(tvm::__mk_TVM11::{lambda(tvm::DiagnosticContext)#1}, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)::{lambda(tvm::runtime::TVMArgs const&, tvm::runtime::TVMRetValue*)#1}> >::Call(tvm::runtime::PackedFuncObj const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, tvm::runtime::TVMRetValue)
  0: tvm::DiagnosticContext::Render()
  File "/home/acer/tvm/src/ir/diagnostic.cc", line 131
DiagnosticError: one or more error diagnostics were emitted, please check diagnostic render for output.

```

### Environment

tvm commit: d8c06767e3e99d888c892fa31a61d02ab21ce90b 
python 3.7.17

### Steps to reproduce

Just import `tvm.tir.tensor_intrin`

### Triage

Please refer to the list of label tags [here](https://github.com/apache/tvm/wiki/Issue-Triage-Labels) to find the relevant tags and add them below in a bullet format (example below).

* needs-triage

**Comment by Hzfengsy** [comment]
Thanks for reporting. However, I cannot reproduce your error with Python 3.9.

As Python 3.7's support is ended (https://endoflife.date/python), could please try a newer Python version?

**Comment by twmht** [comment]
the erros was gone after switching to python3.8
