### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by SlowMonk** [apache/tvm#16984]
Thanks for participating in the TVM community! We use https://discuss.tvm.ai for any general usage questions and discussions. The issue tracker is used for actionable items such as feature proposals discussion, roadmaps, and bug tracking.  You are always welcomed to post on the forum first :smile_cat:

Issues that are inactive for a period of time may get closed. We adopt this policy so that we won't lose track of actionable issues that may fall at the bottom of the pile. Feel free to reopen a new one if you feel there is an additional problem that needs attention when an old one gets closed.

### Expected behavior

What you were expecting
compile 

### Actual behavior

What actually happened

```
python3 setup.py install
/usr/lib/python3/dist-packages/pythran/tables.py:4520: FutureWarning: In the future `np.bool` will be defined as the corresponding NumPy scalar.
  if not hasattr(numpy, method):
/usr/lib/python3/dist-packages/pythran/tables.py:4553: FutureWarning: In the future `np.bytes` will be defined as the corresponding NumPy scalar.
  obj = getattr(themodule, elem)
Compiling tvm/_ffi/_cython/core.pyx because it changed.
[1/1] Cythonizing tvm/_ffi/_cython/core.pyx

Error compiling Cython file:
------------------------------------------------------------
...
        """
        cdef DLManagedTensor* dltensor
        if self.c_is_view != 0:
            raise ValueError("to_dlpack do not work with memory views")
        CALL(TVMArrayToDLPack(self.chandle, &dltensor))
        return pycapsule.PyCapsule_New(dltensor, _c_str_dltensor, _c_dlpack_deleter)
                                                                  ^
------------------------------------------------------------

tvm/_ffi/_cython/./ndarray.pxi:90:66: Cannot assign type 'void (object) except *' to 'PyCapsule_Destructor' (alias of 'void (*)(object) noexcept'). Exception values are incompatible. Suggest adding 'noexcept' to the type of '_c_dlpack_deleter'.
Traceback (most recent call last):
  File "/data/incubator-tvm/python/setup.py", line 160, in <module>
    ext_modules=config_cython(),
  File "/data/incubator-tvm/python/setup.py", line 99, in config_cython
    return cythonize(ret, compiler_directives={"language_level": 3})
  File "/usr/local/lib/python3.10/dist-packages/Cython/Build/Dependencies.py", line 1154, in cythonize
    cythonize_one(*args)
  File "/usr/local/lib/python3.10/dist-packages/Cython/Build/Dependencies.py", line 1321, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: tvm/_ffi/_cython/core.pyx

```
### Environment
jetson agx origin 

Any environment details, such as: Operating System, TVM version, etc

### Steps to reproduce

Preferably a minimal script to cause the issue to occur.

### Triage

Please refer to the list of label tags [here](https://github.com/apache/tvm/wiki/Issue-Triage-Labels) to find the relevant tags and add them below in a bullet format (example below).

* needs-triage

**Comment by haoqian-hao** [comment]
Hi @SlowMonk,

I also met this issue, have you found any way to fix it ? Thank you.

**Comment by KiyoNetcat** [comment]
ran into this also, worked around it by adding `"legacy_implicit_noexcept": True` to the `cythonize`'s `compiler_directives` in `setup.py` (based on https://stackoverflow.com/a/78386418)
