### ISSUE TITLE
[Bug] Building erros for hexagon_launcher

### ISSUE THREAD

**Issue by chayliu-ecarx** [apache/tvm#17193]
When building hexagon_launcher as the guide: https://github.com/apache/tvm/tree/main/apps/hexagon_launcher，there are some errors:

```
tvm/apps/hexagon_launcher/cmake/hexagon/../../../../include/tvm/runtime/container/array.h:661:76: error: no member named 'invoke_result_t' in namespace 'std'
  template <typename F, typename = std::enable_if_t<std::is_same_v<T, std::invoke_result_t<F, T>>>>
                                                                      ~~~~~^
tvm/apps/hexagon_launcher/cmake/hexagon/../../../../include/tvm/runtime/container/array.h:661:92: error: 'F' does not refer to a value
  template <typename F, typename = std::enable_if_t<std::is_same_v<T, std::invoke_result_t<F, T>>>>
                                                                                           ^
tvm/apps/hexagon_launcher/cmake/hexagon/../../../../include/tvm/runtime/container/array.h:661:22: note: declared here
  template <typename F, typename = std::enable_if_t<std::is_same_v<T, std::invoke_result_t<F, T>>>>
                     ^
tvm/apps/hexagon_launcher/cmake/hexagon/../../../../include/tvm/runtime/container/array.h:661:99: error: expected member name or ';' after declaration specifiers
  template <typename F, typename = std::enable_if_t<std::is_same_v<T, std::invoke_result_t<F, T>>>>
                                                                                                  ^
tvm/apps/hexagon_launcher/cmake/hexagon/../../../../include/tvm/runtime/container/array.h:784:43: error: no template named 'invoke_result_t' in namespace 'std'
  template <typename F, typename U = std::invoke_result_t<F, T>>
                                     ~~~~~^
tvm/apps/hexagon_launcher/cmake/hexagon/../../../../include/tvm/runtime/container/array.h:792:47: error: no template named 'is_same_v' in namespace 'std'; did you mean 'is_same'?
```
the hexagon sdk version is 4.5.

@quic-sanirudh
@abhikran-quic
@kparzysz-quic
@sdalvi-quic

**Comment by chayliu-ecarx** [comment]
solved by adding cmake option: `-DCMAKE_CXX_STANDARD=17` .

**Comment by quic-sanirudh** [comment]
> solved by adding cmake option: `-DCMAKE_CXX_STANDARD=17` .

Thanks for the issue. If you're interested, please feel free to send a PR to update the docs so that it's helpful to others.

**Comment by chayliu-ecarx** [comment]
Ok，I will add this to readme.

However,  there are some other questions:
1. Can we import other framework model such as onnx?
2. Can we import a float32 model and using AIMET quantify encoding information?
3. Can we use qnn as the runtime by BYOC?
4. After import the inceptionv4 TFLITE model，and then trying to building for it as:
```
mod, params = relay.frontend.from_tflite(tflite_model)
target = tvm.target.hexagon('v66', hvx=0)
with tvm.transform.PassContext(opt_level=3):
    lib = relay.build(mod, tvm.target.Target(target, host=target), params=params, mod_name="default")
```
there is an error: `LLVM ERROR: Do not know how to split the result of this operator!`

**Comment by quic-sanirudh** [comment]
> Ok，I will add this to readme.
> 
> However, there are some other questions:
> 
> 1. Can we import other framework model such as onnx?
> 2. Can we import a float32 model and using AIMET quantify encoding information?
> 3. Can we use qnn as the runtime by BYOC?
> 4. After import the inceptionv4 TFLITE model，and then trying to building for it as:
> 
> ```
> mod, params = relay.frontend.from_tflite(tflite_model)
> target = tvm.target.hexagon('v66', hvx=0)
> with tvm.transform.PassContext(opt_level=3):
>     lib = relay.build(mod, tvm.target.Target(target, host=target), params=params, mod_name="default")
> ```
> 
> there is an error: `LLVM ERROR: Do not know how to split the result of this operator!`

1. Importing onnx models through onnx importer in relay is supported. There are some examples in hexagon contrib tests you can refer.
2. No. AIMET quantization is not supported in TVM
3. No, we don't support QNN through BYOC. 
4. That sounds like an error in LLVM lowering, which needs to be fixed in LLVM. Please post a separate issue with steps to reproduce and we can try to fix it.

Let me know if it's okay to close this issue as you figured out the fix.

**Comment by chayliu-ecarx** [comment]
Ok, thanks very much for your reply.

I am tring to import and build a onnx model 
```
import numpy as np
import pytest
from tvm import relay
import onnx

onnx_model = onnx.load("mobilenetv2-7.onnx")
input_name = "data"
data_shape = (1, 3, 224, 224)
shape_dict = {input_name:data_shape }

relay_mod, params = relay.frontend.from_onnx(onnx_model, shape_dict)
print(relay_mod)

target = tvm.target.hexagon('v66')
with tvm.transform.PassContext(opt_level=3):
    lib = relay.build(relay_mod, tvm.target.Target(target, host=target), params=params, mod_name="default")
    
with open('mobilenetv2-7.json', 'w') as f:
    f.write(lib.get_graph_json())
lib.get_lib().save('mobilenetv2-7.so')
```

But, It still failed:
```
Traceback (most recent call last):
  File "build_hexagon.py", line 17, in <module>
    lib = relay.build(relay_mod, tvm.target.Target(target, host=target), params=params, mod_name="default")
  File "tvm/python/tvm/relay/build_module.py", line 364, in build
    graph_json, runtime_mod, params = bld_mod.build(
  File "tvm/python/tvm/relay/build_module.py", line 161, in build
    self._build(
  File "tvm/python/tvm/_ffi/_ctypes/packed_func.py", line 240, in __call__
    raise_last_ffi_error()
  File "tvm/python/tvm/_ffi/base.py", line 481, in raise_last_ffi_error
    raise py_err
tvm.error.InternalError: Traceback (most recent call last):
  5: tvm::relay::backend::RelayBuildModule::GetFunction(tvm::runtime::String const&, tvm::runtime::ObjectPtr<tvm::runtime::Object> const&)::{lambda(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)#3}::operator()(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*) const
  4: tvm::relay::backend::RelayBuildModule::BuildRelay(tvm::IRModule, tvm::runtime::String const&)
  3: tvm::TIRToRuntime(tvm::runtime::Map<tvm::Target, tvm::IRModule, void, void> const&, tvm::Target const&)
  2: tvm::codegen::Build(tvm::IRModule, tvm::Target)
  1: tvm::runtime::PackedFuncObj::Extractor<tvm::runtime::PackedFuncSubObj<tvm::runtime::TypedPackedFunc<tvm::runtime::Module (tvm::IRModule, tvm::Target)>::AssignTypedLambda<tvm::runtime::Module (*)(tvm::IRModule, tvm::Target)>(tvm::runtime::Module (*)(tvm::IRModule, tvm::Target), std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)::{lambda(tvm::runtime::TVMArgs const&, tvm::runtime::TVMRetValue*)#1}> >::Call(tvm::runtime::PackedFuncObj const*, tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)
  0: tvm::codegen::BuildHexagon(tvm::IRModule, tvm::Target)
  File "tvm/src/target/llvm/codegen_hexagon.cc", line 642
InternalError: Check failed: (f != nullptr) is false: tvm.contrib.hexagon.link_shared does not to exist, do import tvm.contrib.hexagon
```

**Comment by chayliu-ecarx** [comment]
Ok, I will add this to readme file.
