### ISSUE TITLE
[Bug] [Relax] LiftTransformParams lead to wrong inference results

### ISSUE THREAD

**Issue by Cookiee235** [apache/tvm#17207]
Hi all, I found the inference results before and after using pass `LiftTransformParams` have significant differences.
The bug could be in the implementation of `relax.transform.LiftTransformParams()`.

### Expected behavior

The transform `LiftTransformParams` should not change the inference results of the given model.

### Actual behavior

```
Traceback (most recent call last):
  File "/share_container/optfuzz/res/bugs/27_wrong.py", line 42, in <module>
    np.testing.assert_allclose(before_outputs, after_outputs, rtol=1e-5, atol=1e-5)
  File "/root/.local/lib/python3.12/site-packages/numpy/testing/_private/utils.py", line 1684, in assert_allclose
    assert_array_compare(compare, actual, desired, err_msg=str(err_msg),
  File "/root/miniconda3/lib/python3.12/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.12/site-packages/numpy/testing/_private/utils.py", line 885, in assert_array_compare
    raise AssertionError(msg)
AssertionError:
Not equal to tolerance rtol=1e-05, atol=1e-05

Mismatched elements: 16 / 16 (100%)
Max absolute difference among violations: 10
Max relative difference among violations: 0.5
 ACTUAL: array([24,  5, 16, 70, 72, 90, 42, 32, 50, 49, 24, 15, 18,  8,  4, 40],
      dtype=int32)
 DESIRED: array([16,  4, 14, 63, 63, 80, 36, 28, 40, 42, 16, 10, 15,  7,  0, 36],
      dtype=int32)

```

### Environment

* TVM: 0.17.dev0

### Steps to reproduce
```
import tvm
from tvm import relax
import numpy as np

from tvm.script import ir as I
from tvm.script import relax as R

@I.ir_module
class Module:
    @R.function
    def main(A: R.Tensor((16,), dtype="int32"), B: R.Tensor((16,), dtype="int32")) -> R.Tensor((16,), dtype="int32"):
        R.func_attr({"num_input": 1})
        cls = Module
        with R.dataflow():
            offset = R.ones(R.shape([16]), dtype="int32")
            A_offset = R.add(A, offset)
            B_offset = R.add(B, offset)
            output = R.multiply(A_offset, B_offset)
            R.output(output)
        return output

def compile_mod(mod, target_func, *inputs):
    mod = relax.transform.FuseTIR()(mod)
    mod = relax.transform.LambdaLift()(mod)
    ex = relax.build(mod, target='llvm')
    vm = relax.VirtualMachine(ex, tvm.cpu())
    mod_outputs = vm[f'{target_func}'](*inputs).numpy()
    return mod_outputs


mod = Module
mod = tvm.relax.transform.LegalizeOps()(mod)

input_0 = tvm.nd.array(np.random.randint(10, size=[16]).astype('int32'))
input_1 = tvm.nd.array(np.random.randint(10, size=[16]).astype('int32'))
before_outputs = compile_mod(mod, 'main', input_0,input_1,)

mod = relax.transform.LiftTransformParams()(mod)  # output wrong res due to this transform
after_outputs = compile_mod(mod, 'main', input_0, input_1,)

np.testing.assert_allclose(before_outputs, after_outputs, rtol=1e-5, atol=1e-5)
```

cc @Lunderberg @junrushao @tqchen @vinx13

**Comment by Lunderberg** [comment]
Looks like the test case is correctly lifting out a pre-processing step (the computation of `B_offset`) into a separate function, but the test script doesn't end up running the pre-processing step.  In most cases, this would result in a shape mismatch (e.g. if `matmul_weight = R.permute_dims(linear_weight)` is lifted out), but in this case the shapes of `B` and `B_offset` match.

If I update your test case to call `"main_transform_params"` first, then the results do match.

```python
#!/usr/bin/env python3

import tvm
from tvm import relax
import numpy as np

from tvm.script import ir as I, relax as R


@I.ir_module
class Module:
    @R.function
    def main(A: R.Tensor((16,), dtype="int32"), B: R.Tensor((16,), dtype="int32")) -> R.Tensor(
        (16,), dtype="int32"
    ):
        R.func_attr({"num_input": 1})
        cls = Module
        with R.dataflow():
            offset = R.ones(R.shape([16]), dtype="int32")
            A_offset = R.add(A, offset)
            B_offset = R.add(B, offset)
            output = R.multiply(A_offset, B_offset)
            R.output(output)
        return output


def compile_mod(mod):
    mod = relax.transform.FuseTIR()(mod)
    mod = relax.transform.LambdaLift()(mod)
    ex = relax.build(mod, target="llvm")
    vm = relax.VirtualMachine(ex, tvm.cpu())
    return vm


def main():
    mod = Module
    mod = tvm.relax.transform.LegalizeOps()(mod)

    input_0 = tvm.nd.array(np.random.randint(10, size=[16]).astype("int32"))
    input_1 = tvm.nd.array(np.random.randint(10, size=[16]).astype("int32"))

    compiled_before = compile_mod(mod)
    # Without LiftTransformParams, all parameters are directly
    # accepted as arguments to main.
    before_outputs = compiled_before["main"](input_0, input_1)

    compiled_after = compile_mod(relax.transform.LiftTransformParams()(mod))
    # With LiftTransformParams, preprocessing steps that may be
    # performed on weight parameter (param index >
    # func.attrs['num_input']) are lifted out.
    transformed_weights = compiled_after["main_transform_params"]([input_1])
    # The main function is now called using the transformed weights,
    # rather than the original `input_1`.
    after_outputs = compiled_after["main"](input_0, *transformed_weights)

    np.testing.assert_equal(before_outputs.numpy(), after_outputs.numpy())

if __name__ == "__main__":
    main()

```

**Comment by Cookiee235** [comment]
@Lunderberg Thanks for your detailed explanation. 
I closed this issue due to my invalid test script.

**Comment by Lunderberg** [comment]
No problem, and the fact that there was confusion in the first place probably means that the API/documentation needs improvement.  Where most of the IRModule transforms avoid changing the function signatures at all, especially for publicly-exposed functions, there are a few that do.  (e.g. `BindParams`)

Also, I wanted to say thank you for the detailed bug reports and test cases.  They help quite a bit in defining how the error can be reproduced, and narrowing down where the error is occurring.
