### ISSUE TITLE
[Bug] [Relax]  Expect a not null value of IRModule

### ISSUE THREAD

**Issue by Cookiee235** [apache/tvm#17230]
### Actual behavior

```
Traceback (most recent call last):
  File "test.py", line 22, in <module>
    mod = tvm.relax.transform.LegalizeOps()(mod)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/software/tvm-lunder/python/tvm/ir/transform.py", line 238, in __call__
    return _ffi_transform_api.RunPass(self, mod)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/software/tvm-lunder/python/tvm/_ffi/_ctypes/packed_func.py", line 240, in __call__
    raise_last_ffi_error()
  File "/software/tvm-lunder/python/tvm/_ffi/base.py", line 481, in raise_last_ffi_error
    raise py_err
tvm._ffi.base.TVMError: Traceback (most recent call last):
  1: tvm::runtime::PackedFuncObj::Extractor<tvm::runtime::PackedFuncSubObj<tvm::runtime::TypedPackedFunc<tvm::IRModule (tvm::transform::Pass, tvm::IRModule)>::AssignTypedLambda<tvm::transform::{lambda(tvm::transform::Pass, tvm::IRModule)#7}>(tvm::transform::{lambda(tvm::transform::Pass, tvm::IRModule)#7}, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)::{lambda(tvm::runtime::TVMArgs const&, tvm::runtime::TVMRetValue*)#1}> >::Call(tvm::runtime::PackedFuncObj const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, tvm::runtime::TVMRetValue)
  0: tvm::runtime::TVMMovableArgValueWithContext_::operator tvm::IRModule<tvm::IRModule>() const
  2: tvm::runtime::PackedFuncObj::Extractor<tvm::runtime::PackedFuncSubObj<tvm::runtime::TypedPackedFunc<tvm::IRModule (tvm::transform::Pass, tvm::IRModule)>::AssignTypedLambda<tvm::transform::{lambda(tvm::transform::Pass, tvm::IRModule)#7}>(tvm::transform::{lambda(tvm::transform::Pass, tvm::IRModule)#7}, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)::{lambda(tvm::runtime::TVMArgs const&, tvm::runtime::TVMRetValue*)#1}> >::Call(tvm::runtime::PackedFuncObj const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, tvm::runtime::TVMRetValue)
  1: tvm::runtime::TVMMovableArgValueWithContext_::operator tvm::IRModule<tvm::IRModule>() const
  0: tvm::IRModule tvm::runtime::TVMPODValue_::AsObjectRef<tvm::IRModule>() const
  File "/software/tvm-lunder/include/tvm/runtime/packed_func.h", line 785
TVMError: In function transform.RunPass(0: transform.Pass, 1: IRModule) -> IRModule: error while converting argument 1: [21:44:09] /software/tvm-lunder/include/tvm/runtime/packed_func.h:2022: Check failed: (TObjectRef::_type_is_nullable) is false: Expect a not null value of IRModule
```

### Steps to reproduce

```
import tvm
from tvm import relax

from tvm.script import ir as I
from tvm.script import tir as T
from tvm.script import relax as R

@I.ir_module
class Module:
    @R.function
    def main(v1_0: R.Tensor((1,), dtype="float16"), v6_0: R.Tensor((1, 40, 25, 1), dtype="float16")) -> R.Tensor((), dtype="float16"):
        with R.dataflow():
            lv: R.Tensor((), dtype="float16") = R.sum(v6_0, axis=None, keepdims=False)
            R.output(lv)
        return lv


mod = Module
mod = tvm.relax.transform.DeadCodeElimination()(mod)
mod = mod.show()
mod = tvm.relax.transform.LegalizeOps()(mod)
```

cc @Lunderberg @junrushao

**Comment by Lunderberg** [comment]
> `mod = mod.show()`

This line looks like a bug in the test case.  Displaying a module is not a transform, and so `mod.show()` returns `None`.  This then correctly errors out by detecting the nullptr in the `IRModule`.

(The error message may be improved by making `IRModule` be a non-nullable type, but a lot of the earlier portions of TVM rely on `ObjectRef` sub-types being nullable, so it would be a non-trivial change.  Would need to first find all instances `IRModule` that should be replaced by `Optional<IRModule>`.)

**Comment by Cookiee235** [comment]
@Lunderberg Haha, I'm so sorry for misusing the API. Since I did not understand the error message, I submitted it directly.

Indeed,  improving the error message will be better. If you are willing to improve the error message, I'll leave this issue open. Otherwise, you can feel free to close this issue directly. Thanks!

**Comment by Lunderberg** [comment]
Looking closer, the change that I was thinking of already occurs ([here](https://github.com/apache/tvm/blob/main/include/tvm/ir/module.h#L454)), and `IRModule` is non-nullable.  So, it already indicates (1) that the function signature is `(0: transform.Pass, 1: IRModule)`, (2) that there is a problem with `converting argument 1`, and (3) that the problem is that it was `Expect a not null value of IRModule`.

So, the error message looks like it already gives all of the information it could.  Maybe it could be improved by returning a `TypeError` instead of a `TVMError`, but that would be about the extent of it.

**Comment by Cookiee235** [comment]
@Lunderberg Thanks for your deep investigation. It's not very essential to change the error type from `TVMError` to `TypeError`. I closed it.
