### ISSUE TITLE
[Bug] VTA RPC Error

### ISSUE THREAD

**Issue by zhongwujie** [apache/tvm#17266]
### Environment
* FPGA board: PYNQ Z2
* TVM commit: [6ae2961](https://github.com/apache/tvm/commit/6ae29610a531cea66e94f8bdcf96f2c5cbdb3bf9)
* Host sytem: Ubuntu 22.04.4 LTS

### Steps to reproduce
I follow the guidance in the [VTA document](https://tvm.apache.org/docs/topic/vta/install.html#xilinx-pynq-fpga-setup), and I have built twice in the PYNQ Z2 board. However, when I run rpc test program, it raises an error. The followings are the commands and outputs:

**PYNQ Z2 board**:
* The command is
```
sudo ./apps/vta_rpc/start_rpc_server.sh
```
The output is
```
  2024-08-10 10:53:28.909 INFO bind to 0.0.0.0:9091
  2024-08-10 10:53:30.803 INFO connected from ('10.42.0.1', 59304)
  2024-08-10 10:53:30.807 INFO start serving at /tmp/tmp8393yprq
  2024-08-10 10:53:32.691 INFO finish serving ('10.42.0.1', 59304)
```
**The host**  
* The command is
```
python vta/tests/python/pynq/test_program_rpc.py
```
* The output is
```
Traceback (most recent call last):
  File "/home/zhong/code/frameworks/tvm_test/vta/tests/python/pynq/test_program_rpc.py", line 46, in <module>
    program_rpc_bitstream()
  File "/home/zhong/code/frameworks/tvm_test/vta/tests/python/pynq/test_program_rpc.py", line 36, in program_rpc_bitstream
    program_fpga(remote, path)
  File "/home/zhong/code/frameworks/tvm_test/vta/python/vta/rpc_client.py", line 66, in program_fpga
    fprogram(os.path.basename(bitstream))
  File "/home/zhong/code/frameworks/tvm_test/python/tvm/_ffi/_ctypes/packed_func.py", line 240, in __call__
    raise_last_ffi_error()
  File "/home/zhong/code/frameworks/tvm_test/python/tvm/_ffi/base.py", line 481, in raise_last_ffi_error
    raise py_err
tvm.error.RPCError: Traceback (most recent call last):
  5: tvm::runtime::RPCWrappedFunc::operator()(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*) const
  4: tvm::runtime::RPCClientSession::CallFunc(void*, TVMValue const*, int const*, int, std::function<void (tvm::runtime::TVMArgs)> const&)
  3: tvm::runtime::RPCEndpoint::CallFunc(void*, TVMValue const*, int const*, int, std::function<void (tvm::runtime::TVMArgs)>)
  2: tvm::runtime::RPCEndpoint::HandleUntilReturnEvent(bool, std::function<void (tvm::runtime::TVMArgs)>)
  1: tvm::runtime::RPCEndpoint::EventHandler::HandleProcessPacket(std::function<void (tvm::runtime::TVMArgs)>)
  0: tvm::runtime::RPCEndpoint::EventHandler::HandleReturn(tvm::runtime::RPCCode, std::function<void (tvm::runtime::TVMArgs)>)
  File "/home/zhong/code/frameworks/tvm_test/src/runtime/rpc/rpc_endpoint.cc", line 439
RPCError: Error caught from RPC call:
```
**note**
* In the PYNQ Z2 borad, I turn off the gtest in the config.cmake file, because it raises an error. I think it doesn't matter.
### Triage
* needs-triage

**Comment by Geek3600** [comment]
I have the same problem.

**Comment by jyli559** [comment]
I have the same problem. Have you solved this problem?

**Comment by Haleski47** [comment]
> 我也遇到同样的问题。请问您解决了吗？

hi, i also meet the same problem, may i know how you solve the problem?
