### ISSUE TITLE
CodeGenOpenCL: expect calling_conv equals CallingConv::kDeviceKernelLaunch during autotune

### ISSUE THREAD

**Issue by AD-lite24** [apache/tvm#17577]
### Expected behavior

Autotune to work smoothly

### Actual behavior

Autotune does not work and instead keeps throwing above errors. An instance of the error log is 

```
('Traceback (most recent call last):\n  File "/Users/adityadandwate/miniconda3/envs/tvm-run/lib/python3.10/site-packages/tvm/autotvm/measure/measure_methods.py", line 553, in __call__\n    func, arg_info = _build_func_common(measure_input, self.runtime, **kwargs)\n  File "/Users/adityadandwate/miniconda3/envs/tvm-run/lib/python3.10/site-packages/tvm/autotvm/measure/measure_methods.py", line 505, in _build_func_common\n    func = build(s, args, target=target, runtime=runtime)\n  File "/Users/adityadandwate/miniconda3/envs/tvm-run/lib/python3.10/site-packages/tvm/driver/build_module.py", line 297, in build\n    rt_mod_host = _driver_ffi.tir_to_runtime(annotated_mods, target_host)\n  File "/Users/adityadandwate/miniconda3/envs/tvm-run/lib/python3.10/site-packages/tvm/_ffi/_ctypes/packed_func.py", line 245, in __call__\n    raise_last_ffi_error()\n  File "/Users/adityadandwate/miniconda3/envs/tvm-run/lib/python3.10/site-packages/tvm/_ffi/base.py", line 481, in raise_last_ffi_error\n    raise py_err\ntvm.error.InternalError: Traceback (most recent call last):\n  File "/Users/adityadandwate/foss_repos/tvm/src/target/source/codegen_opencl.cc", line 651\nInternalError: Check failed: (calling_conv == CallingConv::kDeviceKernelLaunch) is false: CodeGenOpenCL: expect calling_conv equals CallingConv::kDeviceKernelLaunch\n', InternalError('Traceback (most recent call last):\n  File "/Users/adityadandwate/foss_repos/tvm/src/target/source/codegen_opencl.cc", line 651\nInternalError: Check failed: (calling_conv == CallingConv::kDeviceKernelLaunch) is false: CodeGenOpenCL: expect calling_conv equals CallingConv::kDeviceKernelLaunch'))
Traceback (most recent call last):
  File "/Users/adityadandwate/miniconda3/envs/tvm-run/lib/python3.10/site-packages/tvm/autotvm/measure/measure_methods.py", line 553, in __call__
    func, arg_info = _build_func_common(measure_input, self.runtime, **kwargs)
  File "/Users/adityadandwate/miniconda3/envs/tvm-run/lib/python3.10/site-packages/tvm/autotvm/measure/measure_methods.py", line 505, in _build_func_common
    func = build(s, args, target=target, runtime=runtime)
  File "/Users/adityadandwate/miniconda3/envs/tvm-run/lib/python3.10/site-packages/tvm/driver/build_module.py", line 297, in build
    rt_mod_host = _driver_ffi.tir_to_runtime(annotated_mods, target_host)
  File "/Users/adityadandwate/miniconda3/envs/tvm-run/lib/python3.10/site-packages/tvm/_ffi/_ctypes/packed_func.py", line 245, in __call__
    raise_last_ffi_error()
  File "/Users/adityadandwate/miniconda3/envs/tvm-run/lib/python3.10/site-packages/tvm/_ffi/base.py", line 481, in raise_last_ffi_error
    raise py_err
tvm.error.InternalError: Traceback (most recent call last):
  File "/Users/adityadandwate/foss_repos/tvm/src/target/source/codegen_opencl.cc", line 651
InternalError: Check failed: (calling_conv == CallingConv::kDeviceKernelLaunch) is false: CodeGenOpenCL: expect calling_conv equals CallingConv::kDeviceKernelLaunch
```

### Environment

Host env: Macos
Target env: OpenCL target running ubuntu

### Steps to reproduce

Same script as the tutorial https://tvm.apache.org/docs/how_to/tune_with_autotvm/tune_relay_mobile_gpu.html

**Comment by AD-lite24** [comment]
`  for (auto [gvar, base_func] : mod->functions) {
    ICHECK(base_func->IsInstance<PrimFuncNode>()) << "CodeGenOpenCL: Can only take PrimFunc";
    auto prim_func = Downcast<PrimFunc>(base_func);
    auto calling_conv = prim_func->GetAttr<Integer>(tvm::attr::kCallingConv);
    ICHECK(calling_conv == CallingConv::kDeviceKernelLaunch)
        << "CodeGenOpenCL: expect calling_conv equals CallingConv::kDeviceKernelLaunch";
    functions.Set(gvar, prim_func);
  }`
  
In the pytorch conversion to IRModule, apparently the calling_conv attr was never set to kDeviceKernelLaunch
