### ISSUE TITLE
NotImplementedError: The following operators are not implemented: ['aten::values']

### ISSUE THREAD

**Issue by cloud-mxd** [apache/tvm#6129]
I'm using file /python/tvm/relay/frontend/pytorch.py to convert pytorch model, but raise error like this:
```text
Traceback (most recent call last):
  File "apply_opt_torch.py", line 193, in <module>
    run_direct()
  File "apply_opt_torch.py", line 166, in run_direct
    mod, params, shape_dict = get_network()
  File "apply_opt_torch.py", line 109, in get_network
    mod, params = relay.frontend.from_pytorch(model, shape_dict)
  File "/data00/maxiandi/opensource/incubator-tvm/python/tvm/relay/frontend/pytorch.py", line 2626, in from_pytorch
    _report_missing_conversion(op_names, convert_map)
  File "/data00/maxiandi/opensource/incubator-tvm/python/tvm/relay/frontend/pytorch.py", line 2112, in _report_missing_conversion
    raise NotImplementedError(msg)
NotImplementedError: The following operators are not implemented: ['aten::values']
```

pytorch == 1.3.1 and tvm is latest

**Comment by cloud-mxd** [comment]
cc @MarisaKirisame

**Comment by masahi** [comment]
I don't think `aten::values` should appear if you use `torch.jit.trace()`. If this is a real issue, please add a reproducible script.
