### ISSUE TITLE
[Rust][WASM] WASM runtime example is broken. 

### ISSUE THREAD

**Issue by jroesch** [apache/tvm#6816]
Recent changes seemed to have broke the Rust WASM example. There is an issue executing the produced WASM code:

```
Error: failed to run main module `target/wasm32-wasi/debug/test-rt-wasm32.wasm`

Caused by:
    0: failed to instantiate "target/wasm32-wasi/debug/test-rt-wasm32.wasm"
    1: command export '__tvm_module_ctx' is not a function
```

cc @ehsanmok

**Comment by jroesch** [comment]
cc @kazum I am not able to reproduce using current instructions on windows, any thoughts?

**Comment by kazum** [comment]
I encountered a different error with the latest main branch.
```
$ wasmtime target/wasm32-wasi/debug/test-rt-wasm32.wasm
Error: failed to run main module `target/wasm32-wasi/debug/test-rt-wasm32.wasm`

Caused by:
    0: failed to invoke `_start`
    1: wasm trap: indirect call type mismatch
       wasm backtrace:
         0: 0x37569 - <unknown>!tvm_graph_rt::module::wrap_backend_packed_func::{{closure}}::hbee2f3ef4e32527e
         1: 0x1a36 - <unknown>!test_rt_wasm32::main::hbb4d387c03ac56d3
         2: 0xe06c - <unknown>!std::rt::lang_start::{{closure}}::h70a400566ab57956
         3: 0x92876 - <unknown>!std::sys_common::backtrace::__rust_begin_short_backtrace::h6103d9a4666ac834
         4: 0x9373e - <unknown>!std::rt::lang_start_internal::ha1eb439644c595a0
         5: 0xe01e - <unknown>!std::rt::lang_start::h230ba3b222020488
         6: 0x1bcd - <unknown>!__original_main
         7: 0x13ae - <unknown>!_start
       
```
Anyway, I'll take a look.

**Comment by jroesch** [comment]
@kazum I did a big of debugging but somehow the test got turned off and seems to have broken, was trying to make it more robust on multiple platforms so we can simplify `task_rush.sh` to use Cargo more.

**Comment by sambitnayak** [comment]
Hitting this issue when experimenting. Any suggestions on this, please?

**Comment by ya0guang** [comment]
I also encountered a similar problem when executing the WASM.

trace:
```sh
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: wasm trap: indirect call type mismatch
wasm backtrace:
    0: 0x926a7 - tvm_graph_rt::module::wrap_backend_packed_func::{{closure}}::hc41b54aab3cb76f6
                    at /home/ya0guang/Code/tvm/rust/tvm-graph-rt/src/module/mod.rs:49:25
    1: 0x31f95 - tvm_graph_rt::graph::GraphExecutor::setup_op_execs::{{closure}}::h796f856bdd94f006
                    at /home/ya0guang/Code/tvm/rust/tvm-graph-rt/src/graph.rs:311:17
    2: 0xc97ad - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::hf5ca8f8ac2b01304
                    at /home/ya0guang/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:1560:9
    3: 0x9e858 - tvm_graph_rt::graph::GraphExecutor::run::{{closure}}::h64f3e6e6888bde03
                    at /home/ya0guang/Code/tvm/rust/tvm-graph-rt/src/graph.rs:204:13
    4: 0x83d82 - <core::slice::iter::Iter<T> as core::iter::traits::iterator::Iterator>::for_each::h71b18dc5ce1e6a4c
                    at /home/ya0guang/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/slice/iter/macros.rs:203:21
    5: 0x9e80e - tvm_graph_rt::graph::GraphExecutor::run::h2fd8fe0d78a2c3ff
                    at /home/ya0guang/Code/tvm/rust/tvm-graph-rt/src/graph.rs:203:9
    6: 0x2bb77 - run
                    at /home/ya0guang/Code/tvm/apps/wasm-standalone-mod/wasm-graph/src/lib.rs:86:5
', src/main.rs:84:22
```
