### ISSUE TITLE
Problems when import BERT model from tensorflow Relay

### ISSUE THREAD

**Issue by fanwei-china** [apache/tvm#6931]
Hi, I was trying to import bert  model by tensorflow relay. When converting the StrideSlice op, an error occurred. Could someone help me to solve this?  The code is as follow:
 Traceback (most recent call last):
     File "tutorials/frontend/test_nlp.py", line 109, in <module>
                        shape=shape_dict)
     File "/root/.local/lib/python3.6/site-packages/tvm-0.7.dev1-py3.6-linux-x86_64.egg/tvm/relay/frontend/tensorflow.py", line 2742, in from_tensorflow
        mod, params = g.from_tensorflow(graph, layout, shape, outputs)
     File "/root/.local/lib/python3.6/site-packages/tvm-0.7.dev1-py3.6-linux-x86_64.egg/tvm/relay/frontend/tensorflow.py", line 2372, in from_tensorflow
op = self._convert_operator(node.op, inputs, attr, graph)
     File "/root/.local/lib/python3.6/site-packages/tvm-0.7.dev1-py3.6-linux-x86_64.egg/tvm/relay/frontend/tensorflow.py", line 2702, in _convert_operator
      sym = convert_map[op_name](inputs, attrs, self._params, self._mod)
   File "/root/.local/lib/python3.6/site-packages/tvm-0.7.dev1-py3.6-linux-x86_64.egg/tvm/relay/frontend/tensorflow.py", line 1145, in _impl 
    out_shape = _infer_shape(out, mod=mod)
   File "/root/.local/lib/python3.6/site-packages/tvm-0.7.dev1-py3.6-linux-x86_64.egg/tvm/relay/frontend/common.py", line 478, in infer_shape      
     out_type = infer_type(inputs, mod=mod)
   File "/root/.local/lib/python3.6/site-packages/tvm-0.7.dev1-py3.6-linux-x86_64.egg/tvm/relay/frontend/common.py", line 470, in infer_type
     new_mod = IRModule.from_expr(node)
  File "/root/.local/lib/python3.6/site-packages/tvm-0.7.dev1-py3.6-linux-x86_64.egg/tvm/ir/module.py", line 226, in from_expr
    return _ffi_api.Module_FromExpr(expr, funcs, defs)
  File "/root/.local/lib/python3.6/site-packages/tvm-0.7.dev1-py3.6-linux-x86_64.egg/tvm/_ffi/_ctypes/packed_func.py", line 213, in __call__
    raise get_last_ffi_error()

**Comment by fanwei-china** [comment]
Traceback (most recent call last):
     File "tutorials/frontend/test_nlp.py", line 109, in <module>
     shape=shape_dict)

     File "/root/.local/lib/python3.6/site-packages/tvm-0.7.dev1-py3.6-linux-x86_64.egg/tvm/relay/frontend/tensorflow.py", line 2742, in from_tensorflow
     mod, params = g.from_tensorflow(graph, layout, shape, outputs)

     File "/root/.local/lib/python3.6/site-packages/tvm-0.7.dev1-py3.6-linux-x86_64.egg/tvm/relay/frontend/tensorflow.py", line 2372, in from_tensorflow
     op = self._convert_operator(node.op, inputs, attr, graph)

    File "/root/.local/lib/python3.6/site-packages/tvm-0.7.dev1-py3.6-linux-x86_64.egg/tvm/relay/frontend/tensorflow.py", line 2702, in _convert_operator
     sym = convert_map[op_name](inputs, attrs, self._params, self._mod)
 
    File "/root/.local/lib/python3.6/site-packages/tvm-0.7.dev1-py3.6-linux-x86_64.egg/tvm/relay/frontend/tensorflow.py", line 1145, in _impl
   out_shape = _infer_shape(out, mod=mod)

    File "/root/.local/lib/python3.6/site-packages/tvm-0.7.dev1-py3.6-linux-x86_64.egg/tvm/relay/frontend/common.py", line 478, in infer_shape
     out_type = infer_type(inputs, mod=mod)

    File "/root/.local/lib/python3.6/site-packages/tvm-0.7.dev1-py3.6-linux-x86_64.egg/tvm/relay/frontend/common.py", line 463, in infer_type
    mod["main"] = _expr.Function(tvm.relay.analysis.free_vars(node), node)

    File "/root/.local/lib/python3.6/site-packages/tvm-0.7.dev1-py3.6-linux-x86_64.egg/tvm/ir/module.py", line 75, in __setitem__
return self._add(var, val)

    File "/root/.local/lib/python3.6/site-packages/tvm-0.7.dev1-py3.6-linux-x86_64.egg/tvm/ir/module.py", line 84, in _add _ffi_api.Module_Add(self, var, val, update)

    File "/root/.local/lib/python3.6/site-packages/tvm-0.7.dev1-py3.6-linux-x86_64.egg/tvm/_ffi/_ctypes/packed_func.py", line 213, in __call__ raise get_last_ffi_error()

**Comment by fanwei-china** [comment]
the IRModule is below:
 fn (%bert/embeddings/word_embedding: Tensor[(249079, 384), float32], %qt_sent: Tensor[(512, 50), int32], %n_keyword_in: Tensor[(512, 10), int32], %bert/embeddings/new_key_imp_embedding: Tensor[(256, 384
   %0 = take(%bert/embeddings/word_embedding, %qt_sent, axis=0);
   %1 = take(%bert/embeddings/word_embedding, %n_keyword_in, axis=0);
   %2 = take(%bert/embeddings/new_key_imp_embedding, %n_keyword_imp, axis=0);
   %3 = add(%1, %2);
   %4 = take(%bert/embeddings/new_key_order_embedding, %n_keyword_occ, axis=0);
   %5 = add(%3, %4);
   %6 = take(%bert/embeddings/doc_embedding, %url_sent, axis=0);
    …
    …
    …
  %565 = reshape(%564, newshape=[32256, 384]);
   %566 = cast(%bert/encoder/layer_3/output/LayerNorm/gamma, dtype="float16");
   %567 = multiply(%565, %566);
   %568 = cast(%bert/encoder/layer_3/output/LayerNorm/beta, dtype="float16");
   %569 = add(%567, %568);
   %570 = reshape(%569, newshape=[512, 63, 384]);
   %571 = cast(%570, dtype="float32");
   strided_slice(%571, begin=[0, 62, 0], end=[512, 63, 384], strides=[1, 1, 1])
 }
 // meta data omitted. you can use show_meta_data=True to include meta data

**Comment by fanwei-china** [comment]
the tensorflow frontend code is:
with tf_compat_v1.gfile.GFile(model_path, 'rb') as f:
      graph_def = tf_compat_v1.GraphDef()
      graph_def.ParseFromString(f.read())
      graph = tf.import_graph_def(graph_def, name='')
      # Call the utility to import the graph definition into default graph.
      graph_def = tf_testing.ProcessGraphDefParam(graph_def)
      # Add shapes to the graph.
      with tf_compat_v1.Session() as sess:
          graph_def = tf_testing.AddShapesToGraphDef(sess, 'bert/cls/predictions/label_score')
 
  qt = np.full((512, 50), 1, "int32")
  qt_mask = np.full((512, 50), 1.1, "float32")
  site = np.full((512, 1), 1, "int32")
  o_k = np.full((512, 10), 1, "int32")
  o_k_m = np.full((512, 10), 1.1, "float32")
  n_k = np.full((512, 10), 1, "int32")
  n_k_m = np.full((512, 10), 1.1, "float32")
  n_k_i = np.full((512, 10), 1, "int32")
  n_k_o = np.full((512, 10), 1, "int32")
 
  # Import the graph to Relay
  # -------------------------
  # Import tensorflow graph definition to relay frontend.
  #
  # Results:
  #   sym: relay expr for given tensorflow protobuf.
  #   params: params converted from tensorflow params (tensor protobuf).
  shape_dict = {
          'qt_sent': qt.shape,
          'qt_mask': qt_mask.shape,
          'url_sent': site.shape,
          'keyword_in': o_k.shape,
         'keyword_mask': o_k_m.shape,
         'n_keyword_in': n_k.shape,
         'n_keyword_mask':n_k_m.shape,
         'n_keyword_imp': n_k_i.shape,
         'n_keyword_occ': n_k_o.shape}

  mod, params = relay.frontend.from_tensorflow(graph_def,
                                             layout=layout,
                                              shape=shape_dic)

**Comment by fanwei-china** [comment]
> ```
> Hi, I was trying to import bert  model by tensorflow relay. When converting the StrideSlice op, an error occurred. Could someone help me to solve this?  The code is as follow:
> ```
> 
> Traceback (most recent call last):
> File "tutorials/frontend/test_nlp.py", line 109, in
> shape=shape_dict)
> File "/root/.local/lib/python3.6/site-packages/tvm-0.7.dev1-py3.6-linux-x86_64.egg/tvm/relay/frontend/tensorflow.py", line 2742, in from_tensorflow
> mod, params = g.from_tensorflow(graph, layout, shape, outputs)
> File "/root/.local/lib/python3.6/site-packages/tvm-0.7.dev1-py3.6-linux-x86_64.egg/tvm/relay/frontend/tensorflow.py", line 2372, in from_tensorflow
> op = self._convert_operator(node.op, inputs, attr, graph)
> File "/root/.local/lib/python3.6/site-packages/tvm-0.7.dev1-py3.6-linux-x86_64.egg/tvm/relay/frontend/tensorflow.py", line 2702, in _convert_operator
> sym = convert_map[op_name](inputs, attrs, self._params, self._mod)
> File "/root/.local/lib/python3.6/site-packages/tvm-0.7.dev1-py3.6-linux-x86_64.egg/tvm/relay/frontend/tensorflow.py", line 1145, in _impl
> out_shape = _infer_shape(out, mod=mod)
> File "/root/.local/lib/python3.6/site-packages/tvm-0.7.dev1-py3.6-linux-x86_64.egg/tvm/relay/frontend/common.py", line 478, in infer_shape
> out_type = infer_type(inputs, mod=mod)
> File "/root/.local/lib/python3.6/site-packages/tvm-0.7.dev1-py3.6-linux-x86_64.egg/tvm/relay/frontend/common.py", line 470, in infer_type
> new_mod = IRModule.from_expr(node)
> File "/root/.local/lib/python3.6/site-packages/tvm-0.7.dev1-py3.6-linux-x86_64.egg/tvm/ir/module.py", line 226, in from_expr
> return _ffi_api.Module_FromExpr(expr, funcs, defs)
> File "/root/.local/lib/python3.6/site-packages/tvm-0.7.dev1-py3.6-linux-x86_64.egg/tvm/_ffi/_ctypes/packed_func.py", line 213, in **call**
> raise get_last_ffi_error()

**Comment by junrushao1994** [comment]
Thanks for reporting. We use the discussion forum (https://discuss.tvm.apache.org/) for general usage issues. Please open a thread in the forum. Thanks!
