### ISSUE TITLE
[Bug] Error when compiling a simple ONNX model for opt_level=3

### ISSUE THREAD

**Issue by luyaor** [apache/tvm#7201]
## Description

When compiling following model with opt_level=3, TVM will crash. While if turn opt_level to 2, it will run normally.

The model(with ONNX as frontend) with error is as follows, check bug.onnx in bug1.zip.
![image](https://user-images.githubusercontent.com/7541296/103531448-4c901680-4ec4-11eb-8fcc-591dcb46165c.png)

## Error Log

```
Traceback (most recent call last):
  File "check.py", line 19, in <module>
    tvm_graph, tvm_lib, tvm_params = relay.build_module.build(mod, target, params=params)
  File "/Users/luyaor/Documents/tvm/python/tvm/relay/build_module.py", line 275, in build
    graph_json, mod, params = bld_mod.build(mod, target, target_host, params)
  File "/Users/luyaor/Documents/tvm/python/tvm/relay/build_module.py", line 138, in build
    self._build(mod, target, target_host)
  File "/Users/luyaor/Documents/tvm/python/tvm/_ffi/_ctypes/packed_func.py", line 237, in __call__
    raise get_last_ffi_error()
tvm._ffi.base.TVMError: Traceback (most recent call last):
  [bt] (8) 9   libtvm.dylib                        0x0000000111b9b2a0 tvm::NodeFunctor<void (tvm::runtime::ObjectRef const&, tvm::relay::ExprFunctor<void (tvm::RelayExpr const&)>*)>::operator()(tvm::runtime::ObjectRef const&, tvm::relay::ExprFunctor<void (tvm::RelayExpr const&)>*) const + 288
  [bt] (7) 8   libtvm.dylib                        0x0000000111c8c289 tvm::relay::IndexedForwardGraph::Creator::VisitExpr_(tvm::relay::FunctionNode const*) + 297
  [bt] (6) 7   libtvm.dylib                        0x0000000111e03015 tvm::relay::ExprVisitor::VisitExpr_(tvm::relay::FunctionNode const*) + 149
  [bt] (5) 6   libtvm.dylib                        0x0000000111e02b58 tvm::relay::ExprVisitor::VisitExpr(tvm::RelayExpr const&) + 344
  [bt] (4) 5   libtvm.dylib                        0x0000000111b9afad tvm::relay::ExprFunctor<void (tvm::RelayExpr const&)>::VisitExpr(tvm::RelayExpr const&) + 173
  [bt] (3) 4   libtvm.dylib                        0x0000000111b9b2a0 tvm::NodeFunctor<void (tvm::runtime::ObjectRef const&, tvm::relay::ExprFunctor<void (tvm::RelayExpr const&)>*)>::operator()(tvm::runtime::ObjectRef const&, tvm::relay::ExprFunctor<void (tvm::RelayExpr const&)>*) const + 288
  [bt] (2) 3   libtvm.dylib                        0x0000000111c8c5c3 tvm::relay::IndexedForwardGraph::Creator::VisitExpr_(tvm::relay::CallNode const*) + 659
  [bt] (1) 2   libtvm.dylib                        0x00000001111f36d8 tvm::AttrRegistryMapContainerMap<tvm::Op>::operator[](tvm::Op const&) const + 408
  [bt] (0) 1   libtvm.dylib                        0x0000000111083c6f dmlc::LogMessageFatal::~LogMessageFatal() + 111
  File "/Users/luyaor/Documents/tvm/include/tvm/node/attr_registry_map.h", line 61
TVMError: 
---------------------------------------------------------------
An internal invariant was violated during the execution of TVM.
Please read TVM's error reporting guidelines.
More details can be found here: https://discuss.tvm.ai/t/error-reporting/7793.
---------------------------------------------------------------
  Check failed: idx < data_.size() && data_[idx].second != 0 == false: Attribute TOpPattern has not been registered for nn.dropout
```

### Environment

Python3, with tvm, onnx

tvm version: c31e338d5f98a8e8c97286c5b93b20caee8be602 Wed Dec 9 14:52:58 2020 +0900

1. Download 
[bug1.zip](https://github.com/apache/tvm/files/5764418/bug1.zip)

2. Run `python check.py`.

**Comment by mbrookhart** [comment]
This is simply because the DynamicToStatic pass is defined at opt level 3, not 2. We 
can lower it to make this pass, if we think that's a robust thing to do more generally. 

cc @tqchen @jroesch @masahi @jwfromm

**Comment by mbrookhart** [comment]
I will debug this morning.
