### ISSUE TITLE
[FRONTEND][COREML] Support Op LoadConstantNDLayerParams

### ISSUE THREAD

**Issue by asimniazi63** [apache/tvm#7504]
Hi, I am trying to get predictions from CoreML model and I got this error. Pasted below:

Traceback (most recent call last):
  File "tvm_coreml.py", line 25, in <module>
    mod, params = relay.frontend.from_coreml(mlmodel, shape_dict)
  File "/home/asim/.local/lib/python3.8/site-packages/tvm-0.8.dev609+gcfe88c1ee-py3.8-linux-x86_64.egg/tvm/relay/frontend/coreml.py", line 593, in from_coreml
    coreml_op_to_relay(layerop, list(l.input), l.output, etab)
  File "/home/asim/.local/lib/python3.8/site-packages/tvm-0.8.dev609+gcfe88c1ee-py3.8-linux-x86_64.egg/tvm/relay/frontend/coreml.py", line 513, in coreml_op_to_relay
    raise tvm.error.OpNotImplemented(
tvm.error.OpNotImplemented: Operator LoadConstantNDLayerParams is not supported in frontend CoreML.

Code:
```
image = np.expand_dims(image, 0)
mask = np.expand_dims(mask, 0)


target = "llvm"
shape_dict = {"import/image:0": image, "import/mask:0": mask }

# Parse CoreML model and convert into Relay computation graph
mod, params = relay.frontend.from_coreml(mlmodel, shape_dict)
```

**Comment by alejandroarmas** [comment]
Hi @tqchen I've been looking at a few of the TVM talks this past week and I think TVM is an interesting project. I'm working with an M1 chip, so do you think this is a good first PR to tackle? Thanks and hope to hear from you soon.
