### ISSUE TITLE
[Web] tvmjs runtime error when loading, missing "runtime.SystemLib"

### ISSUE THREAD

**Issue by majercakdavid** [apache/tvm#7734]
I would like to report a problem with the JS runtime. Currently when being run the instantiation of tvm run smoothly, not resulting in any error:
```
try {
    this.tvm = await tvmjs.instantiate(
        wasmSource,
        new EmccWASI()
    );
} catch(e){
    console.log(e);
}
```
However, after invoking this line (just like proposed in the https://github.com/apache/tvm/blob/main/web/tests/node/test_module_load.js):

```
this.sysLib = this.tvm.systemLib();
```

The application ended up with the following error:

```
tvmjs_runtime.wasi.js:formatted:410 Uncaught (in promise) RuntimeError: abort([object Object]). Build with -s ASSERTIONS=1 for more info.
    at abort (https://localhost:4443/tvm/wasm/tvmjs_runtime.wasi.js:3:9079)
    at _proc_exit (https://localhost:4443/tvm/wasm/tvmjs_runtime.wasi.js:3:66932)
    at <anonymous>:wasm-function[1680]:0x75969
    at <anonymous>:wasm-function[1683]:0x759d0
    at <anonymous>:wasm-function[188]:0x1eb8b
    at <anonymous>:wasm-function[193]:0x1f194
    at <anonymous>:wasm-function[866]:0x47c0f
    at TVMFuncCall (<anonymous>:wasm-function[78]:0x85e8)
    at packedFunc (https://localhost:4443/tvm/tvmjs.bundle.js:1877:46)
    at Instance.systemLib (https://localhost:4443/tvm/tvmjs.bundle.js:1466:22)
```
Furthermore, I have been able to investigate it a little bit more and the issue most probably lies in here:

![image](https://user-images.githubusercontent.com/9350520/112303774-f8aff500-8c9c-11eb-8b16-223b2dc7f776.png)

**Comment by tqchen** [comment]
Thanks @majercakdavid  Please make sure that wasm_runtime tvmjs_support are linked in your wasm. It is interesting that the partcular function is not registered, as it is done in https://github.com/apache/tvm/blob/main/src/runtime/system_library.cc#L71

as part of here https://github.com/apache/tvm/blob/main/web/emcc/wasm_runtime.cc#L53

I checked with the nodejs testcase and it seems to run fine(and the function is available). If you can try to confirm in a node env we can look further.

The community uses https://discuss.tvm.apache.org/ for general trouble shooting, we can followup there.
