### ISSUE TITLE
`relay.vm.compile()` get a error `Cannot store int32 to buffer of int64`

### ISSUE THREAD

**Issue by vicalloy** [apache/tvm#7896]
1. I get the follow error when run `relay.vm.compile`.
```
Check failed: (dtype.element_of() == n->dtype.element_of() && dtype.lanes() % n->dtype.lanes() == 0) is false: Cannot store int32 to buffer of int64
```

2. The follow code is used to compile the model.
```python
# model from openvino. https://github.com/openvinotoolkit/open_model_zoo/blob/master/models/intel/face-detection-0200/description/face-detection-0200.md
onnx_model = onnx.load('face-detection-0200.onnx')

shape_dict = {
        "image": [1,3,256,256],
        }

mod, params = relay.frontend.from_onnx(onnx_model, shape_dict)
with tvm.transform.PassContext(opt_level=3):
    vm = relay.vm.compile(mod, target="llvm", target_host=None, params=params)

```
3. error on `ubuntu 20.04`
```log
Traceback (most recent call last):
  File "run-tvm.py", line 34, in <module>
    vm = relay.vm.compile(mod, target="llvm", target_host=None, params=params)
  File "/home/hu/tvm/python/tvm/relay/backend/vm.py", line 72, in compile
    compiler.lower(mod, target)
  File "/home/hu/tvm/python/tvm/relay/backend/vm.py", line 143, in lower
    self._lower(mod, target, target_host)
  File "/home/hu/tvm/python/tvm/_ffi/_ctypes/packed_func.py", line 237, in __call__
    raise get_last_ffi_error()
tvm._ffi.base.TVMError: Traceback (most recent call last):
  54: TVMFuncCall
  53: std::_Function_handler<void (tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*), tvm::relay::vm::VMCompiler::GetFunction(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, tvm::runtime::ObjectPtr<tvm::runtime::Object> const&)::{lambda(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)#1}>::_M_invoke(std::_Any_data const&, tvm::runtime::TVMArgs&&, tvm::runtime::TVMRetValue*&&)
  52: tvm::relay::vm::VMCompiler::Lower(tvm::IRModule, tvm::runtime::Map<tvm::Integer, tvm::Target, void, void> const&, tvm::Target const&)
  51: tvm::relay::vm::VMCompiler::OptimizeModule(tvm::IRModule, tvm::runtime::Map<tvm::Integer, tvm::Target, void, void> const&, tvm::Target const&)
  50: tvm::transform::Pass::operator()(tvm::IRModule) const
  49: tvm::transform::SequentialNode::operator()(tvm::IRModule, tvm::transform::PassContext const&) const
  48: tvm::transform::Pass::operator()(tvm::IRModule, tvm::transform::PassContext const&) const
  47: tvm::transform::SequentialNode::operator()(tvm::IRModule, tvm::transform::PassContext const&) const
  46: tvm::transform::Pass::operator()(tvm::IRModule, tvm::transform::PassContext const&) const
  45: tvm::transform::ModulePassNode::operator()(tvm::IRModule, tvm::transform::PassContext const&) const
  44: std::_Function_handler<void (tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*), tvm::runtime::TypedPackedFunc<tvm::IRModule (tvm::IRModule, tvm::transform::PassContext)>::AssignTypedLambda<tvm::relay::transform::ManifestAlloc(tvm::Target, tvm::runtime::Map<tvm::Integer, tvm::Target, void, void>)::{lambda(tvm::IRModule, tvm::transform::PassContext const&)#1}>(tvm::relay::transform::ManifestAlloc(tvm::Target, tvm::runtime::Map<tvm::Integer, tvm::Target, void, void>)::{lambda(tvm::IRModule, tvm::transform::PassContext const&)#1})::{lambda(tvm::runtime::TVMArgs const&, tvm::runtime::TVMRetValue*)#1}>::_M_invoke(std::_Any_data const&, tvm::runtime::TVMArgs&&, tvm::runtime::TVMRetValue*&&)
  43: tvm::relay::ExprMutator::VisitExpr(tvm::RelayExpr const&)
  42: _ZZN3tvm5relay11ExprFunctorIFNS_9RelayExprERKS2_EE10InitVTableEvENUlRKNS_7r
  41: tvm::relay::ExprMutator::VisitExpr_(tvm::relay::FunctionNode const*)
  40: tvm::relay::ExprMutator::VisitExpr(tvm::RelayExpr const&)
  39: _ZZN3tvm5relay11ExprFunctorIFNS_9RelayExprERKS2_EE10InitVTableEvENUlRKNS_7r
  38: tvm::relay::DialectRewriter::VisitExpr_(tvm::relay::LetNode const*)
  37: tvm::relay::ExprMutator::VisitExpr(tvm::RelayExpr const&)
  36: _ZZN3tvm5relay11ExprFunctorIFNS_9RelayExprERKS2_EE10InitVTableEvENUlRKNS_7r
  35: tvm::relay::DialectRewriter::VisitExpr_(tvm::relay::CallNode const*)
  34: tvm::relay::DialectRewriter::DynamicInvoke(tvm::relay::LetList*, tvm::relay::Function const&, tvm::relay::Tuple const&, std::vector<tvm::RelayExpr, std::allocator<tvm::RelayExpr> > const&, std::vector<tvm::TensorType, std::allocator<tvm::TensorType> > const&, tvm::Type const&)
  33: tvm::relay::DialectRewriter::EmitShapeFunc(tvm::relay::LetList*, tvm::relay::Function const&, std::vector<tvm::RelayExpr, std::allocator<tvm::RelayExpr> > const&)
  32: tvm::relay::CompileEngineImpl::LowerShapeFunc(tvm::relay::CCacheKey const&)
  31: tvm::relay::CompileEngineImpl::LowerShapeFuncInternal(tvm::relay::CCacheKey const&)
  30: tvm::lower(tvm::te::Schedule, tvm::runtime::Array<tvm::te::Tensor, void> const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::unordered_map<tvm::te::Tensor, tvm::tir::Buffer, std::hash<tvm::te::Tensor>, std::equal_to<tvm::te::Tensor>, std::allocator<std::pair<tvm::te::Tensor const, tvm::tir::Buffer> > > const&)
  29: tvm::transform::Pass::operator()(tvm::IRModule) const
  28: tvm::transform::SequentialNode::operator()(tvm::IRModule, tvm::transform::PassContext const&) const
  27: tvm::transform::Pass::operator()(tvm::IRModule, tvm::transform::PassContext const&) const
  26: tvm::tir::transform::PrimFuncPassNode::operator()(tvm::IRModule, tvm::transform::PassContext const&) const
  25: std::_Function_handler<void (tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*), tvm::runtime::TypedPackedFunc<tvm::tir::PrimFunc (tvm::tir::PrimFunc, tvm::IRModule, tvm::transform::PassContext)>::AssignTypedLambda<tvm::tir::transform::StorageFlatten(int, bool)::{lambda(tvm::tir::PrimFunc, tvm::IRModule, tvm::transform::PassContext)#1}>(tvm::tir::transform::StorageFlatten(int, bool)::{lambda(tvm::tir::PrimFunc, tvm::IRModule, tvm::transform::PassContext)#1})::{lambda(tvm::runtime::TVMArgs const&, tvm::runtime::TVMRetValue*)#1}>::_M_invoke(std::_Any_data const&, tvm::runtime::TVMArgs&&, tvm::runtime::TVMRetValue*&&)
  24: tvm::tir::StorageFlatten(tvm::tir::PrimFunc, int, bool)
  23: tvm::tir::StmtMutator::VisitStmt(tvm::tir::Stmt const&)
  22: _ZZN3tvm3tir11StmtFunctorIFNS0_4StmtERKS2_EE10InitVTableEvENUlRKNS_7runtime
  21: tvm::tir::StorageFlattener::VisitStmt_(tvm::tir::AttrStmtNode const*)
  20: tvm::tir::StmtMutator::VisitStmt(tvm::tir::Stmt const&)
  19: _ZZN3tvm3tir11StmtFunctorIFNS0_4StmtERKS2_EE10InitVTableEvENUlRKNS_7runtime
  18: tvm::tir::StorageFlattener::VisitStmt_(tvm::tir::AttrStmtNode const*)
  17: tvm::tir::StmtMutator::VisitStmt(tvm::tir::Stmt const&)
  16: _ZZN3tvm3tir11StmtFunctorIFNS0_4StmtERKS2_EE10InitVTableEvENUlRKNS_7runtime
  15: tvm::tir::StorageFlattener::VisitStmt_(tvm::tir::BufferRealizeNode const*)
  14: tvm::tir::StmtMutator::VisitStmt(tvm::tir::Stmt const&)
  13: _ZZN3tvm3tir11StmtFunctorIFNS0_4StmtERKS2_EE10InitVTableEvENUlRKNS_7runtime
  12: tvm::tir::StorageFlattener::VisitStmt_(tvm::tir::BufferRealizeNode const*)
  11: tvm::tir::StmtMutator::VisitStmt(tvm::tir::Stmt const&)
  10: _ZZN3tvm3tir11StmtFunctorIFNS0_4StmtERKS2_EE10InitVTableEvENUlRKNS_7runtime
  9: tvm::tir::StorageFlattener::VisitStmt_(tvm::tir::AttrStmtNode const*)
  8: tvm::tir::StmtMutator::VisitStmt_(tvm::tir::AttrStmtNode const*)
  7: tvm::tir::StmtMutator::VisitStmt(tvm::tir::Stmt const&)
  6: _ZZN3tvm3tir11StmtFunctorIFNS0_4StmtERKS2_EE10InitVTableEvENUlRKNS_7runtime9Ob
  5: tvm::tir::StmtMutator::VisitStmt_(tvm::tir::SeqStmtNode const*)
  4: void tvm::runtime::Array<tvm::tir::Stmt, void>::MutateByApply<tvm::tir::StmtMutator::Internal::Mutate(tvm::tir::StmtMutator*, tvm::runtime::Array<tvm::tir::Stmt, void> const&)::{lambda(tvm::tir::Stmt const&)#1}>(tvm::tir::StmtMutator::Internal::Mutate(tvm::tir::StmtMutator*, tvm::runtime::Array<tvm::tir::Stmt, void> const&)::{lambda(tvm::tir::Stmt const&)#1})
  3: tvm::tir::StmtMutator::VisitStmt(tvm::tir::Stmt const&)
  2: _ZZN3tvm3tir11StmtFunctorIFNS0_4StmtERKS2_EE10InitVTableEvENUlRKNS_7runtime
  1: tvm::tir::StorageFlattener::VisitStmt_(tvm::tir::BufferStoreNode const*)
  0: tvm::tir::Buffer::vstore(tvm::runtime::Array<tvm::PrimExpr, void>, tvm::PrimExpr) const
  File "/home/hu/tvm/src/tir/ir/buffer.cc", line 304
TVMError: 
---------------------------------------------------------------
An internal invariant was violated during the execution of TVM.
Please read TVM's error reporting guidelines.
More details can be found here: https://discuss.tvm.ai/t/error-reporting/7793.
---------------------------------------------------------------
  Check failed: (dtype.element_of() == n->dtype.element_of() && dtype.lanes() % n->dtype.lanes() == 0) is false: Cannot store int32 to buffer of int64
```

**Comment by masahi** [comment]
Can you attach the onnx model or tell me how to download it?

**Comment by vicalloy** [comment]
The model: [face-detection-0200.zip](https://github.com/apache/tvm/files/6355080/face-detection-0200.zip)

**Comment by masahi** [comment]
ok thanks reproduced. At first sight it is not clear what operator is causing the issue.

**Comment by masahi** [comment]
This error is fixed by replacing `3` below with `int64(3)` https://github.com/apache/tvm/blob/390b4d1ce32533810fc8d65dcf211f6d147764aa/python/tvm/relay/op/vision/_vision.py#L97

But I got different error.

**Comment by masahi** [comment]
ok can you try replacing 
https://github.com/apache/tvm/blob/8e23806d2d522b71979d0a2730b38cc5c3bf6185/python/tvm/relay/op/_transform.py#L1017-L1023

with

```
@_reg.register_shape_func("where", False)
def where_shape_func(attrs, inputs, _):
    """
    Shape func for where.
    """
    def maybe_expand(tensor):
        if len(tensor.shape) == 0:
            return topi.full((1,), "int64", 1)
        return tensor

    cond_shape = maybe_expand(inputs[0])
    x_shape = maybe_expand(inputs[1])
    y_shape = maybe_expand(inputs[2])
```
With two fixes above `relay.vm.compile` finishes without error. Can you verify the output?

**Comment by vicalloy** [comment]
1. I got another error:
```
[21:09:04] /home/hu/tvm/src/relay/transforms/let_list.h:54: Warning: letlist not used
Traceback (most recent call last):
  File "run-tvm.py", line 25, in <module>
    exe = relay.vm.compile(mod, target="llvm", target_host=None, params=params)
  File "/home/hu/tvm/python/tvm/relay/backend/vm.py", line 72, in compile
    compiler.lower(mod, target)
  File "/home/hu/tvm/python/tvm/relay/backend/vm.py", line 143, in lower
    self._lower(mod, target, target_host)
  File "/home/hu/tvm/python/tvm/_ffi/_ctypes/packed_func.py", line 237, in __call__
    raise get_last_ffi_error()
tvm._ffi.base.TVMError: Traceback (most recent call last):
  53: TVMFuncCall
  52: std::_Function_handler<void (tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*), tvm::relay::vm::VMCompiler::GetFunction(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, tvm::runtime::ObjectPtr<tvm::runtime::Object> const&)::{lambda(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)#1}>::_M_invoke(std::_Any_data const&, tvm::runtime::TVMArgs&&, tvm::runtime::TVMRetValue*&&)
  51: tvm::relay::vm::VMCompiler::Lower(tvm::IRModule, tvm::runtime::Map<tvm::Integer, tvm::Target, void, void> const&, tvm::Target const&)
  50: tvm::relay::vm::VMCompiler::OptimizeModule(tvm::IRModule, tvm::runtime::Map<tvm::Integer, tvm::Target, void, void> const&, tvm::Target const&)
  49: tvm::transform::Pass::operator()(tvm::IRModule) const
....
....
....
  3: tvm::relay::backend::MemoizedExprTranslator<tvm::runtime::Array<tvm::te::Tensor, void> >::VisitExpr(tvm::RelayExpr const&)
  2: _ZZN3tvm5relay11ExprFunctorIFNS_7runtime5ArrayINS_2te6TensorEvEERKNS_9Relay
  1: tvm::relay::MakeShapeFunc::VisitExpr_(tvm::relay::CallNode const*)
  0: std::_Function_handler<void (tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*), TVMFuncCreateFromCFunc::{lambda(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)#2}>::_M_invoke(std::_Any_data const&, tvm::runtime::TVMArgs&&, tvm::runtime::TVMRetValue*&&) [clone .cold]
  File "/home/hu/tvm/python/tvm/_ffi/_ctypes/packed_func.py", line 81, in cfun
    rv = local_pyfunc(*pyargs)
  File "/home/hu/tvm/python/tvm/relay/op/_transform.py", line 1030, in where_shape_func
    bcast_shape = _broadcast_shape_tensors(x_shape, y_shape)
  File "<decorator-gen-214>", line 2, in _broadcast_shape_tensors
  File "/home/hu/tvm/python/tvm/te/hybrid/__init__.py", line 60, in wrapped_func
    return source_to_op(src, args, func.__globals__, closure_vars)
  File "/home/hu/tvm/python/tvm/te/hybrid/parser.py", line 635, in source_to_op
    parser = parse_python(src, args, symbols, closure_vars)
  File "/home/hu/tvm/python/tvm/te/hybrid/parser.py", line 605, in parse_python
    parser.parsed_body = parser.visit(root)
  File "/usr/lib/python3.8/ast.py", line 363, in visit
    return visitor(node)
  File "/home/hu/tvm/python/tvm/te/hybrid/parser.py", line 230, in visit_Module
    return self.visit(node.body[0])
  File "/usr/lib/python3.8/ast.py", line 363, in visit
    return visitor(node)
  File "/home/hu/tvm/python/tvm/te/hybrid/parser.py", line 243, in visit_FunctionDef
    res = visit_list_to_block(self.visit, node.body)
  File "/home/hu/tvm/python/tvm/te/hybrid/parser.py", line 58, in visit_list_to_block
    lst = [visit(stmt) for stmt in lst if not utils.is_docstring(stmt)]
  File "/home/hu/tvm/python/tvm/te/hybrid/parser.py", line 58, in <listcomp>
    lst = [visit(stmt) for stmt in lst if not utils.is_docstring(stmt)]
  File "/usr/lib/python3.8/ast.py", line 363, in visit
    return visitor(node)
  File "/home/hu/tvm/python/tvm/te/hybrid/parser.py", line 304, in visit_Assign
    rhs = self.visit(node.value)
  File "/usr/lib/python3.8/ast.py", line 363, in visit
    return visitor(node)
  File "/home/hu/tvm/python/tvm/te/hybrid/parser.py", line 387, in visit_Subscript
    arr = arr[i.value]
  File "/home/hu/tvm/python/tvm/ir/container.py", line 36, in __getitem__
    return getitem_helper(self, _ffi_api.ArrayGetItem, len(self), idx)
  File "/home/hu/tvm/python/tvm/runtime/container.py", line 57, in getitem_helper
    raise IndexError("Index out of range. size: {}, got index {}".format(length, idx))
IndexError: Index out of range. size: 0, got index 0
```

2. The change:
```diff
diff --git a/python/tvm/relay/op/_transform.py b/python/tvm/relay/op/_transform.py
index 16262833d..05632e60a 100644
--- a/python/tvm/relay/op/_transform.py
+++ b/python/tvm/relay/op/_transform.py
@@ -1018,7 +1018,12 @@ def where_shape_func(attrs, inputs, _):
     """
     Shape func for where.
     """
-    cond_shape = inputs[0]
+    def maybe_expand(tensor):
+        if len(tensor.shape) == 0:
+            return topi.full((1,), "int64", 1)
+        return tensor
+
+    cond_shape = maybe_expand(inputs[0])
     x_shape = inputs[1]
     y_shape = inputs[2]
 
diff --git a/python/tvm/relay/op/vision/_vision.py b/python/tvm/relay/op/vision/_vision.py
index 7a31bce5a..8d6abf1a8 100644
--- a/python/tvm/relay/op/vision/_vision.py
+++ b/python/tvm/relay/op/vision/_vision.py
@@ -94,7 +94,7 @@ def _all_class_nms_shape_func(boxes_shape, scores_shape):
     count_shape = output_tensor((1,), "int64")
 
     out_shape[0] = boxes_shape[0] * scores_shape[1] * boxes_shape[1]
-    out_shape[1] = 3
+    out_shape[1] = int64(3)
     count_shape[0] = int64(1)
     return out_shape, count_shape
```

**Comment by masahi** [comment]
See my change above. You need to wrap `x_shape` and `y_shape` too.

```

    cond_shape = maybe_expand(inputs[0])
    x_shape = maybe_expand(inputs[1])
    y_shape = maybe_expand(inputs[2])
```

**Comment by vicalloy** [comment]
thanks, the output is correct.

**Comment by masahi** [comment]
Great I'll send PRs for the fix tonight.
