### ISSUE TITLE
TypeError: auto_scheduler.RPCRunner is not registered via TVM_REGISTER_NODE_TYPE

### ISSUE THREAD

**Issue by lllggghhh1** [apache/tvm#8053]
Hello, while building the tune_network_cuda.py ( Auto-scheduling a Neural Network for NVIDIA GPU)in TVM , I got the following error:  TypeError: auto_scheduler.RPCRunner is not registered via TVM_REGISTER_NODE_TYPE

Could anyone help me ?

The error:

Traceback (most recent call last):
  File "/tvm-py/tune_network_cuda.py", line 201, in <module>
    run_tuning()
  File "/tvm-py/tune_network_cuda.py", line 192, in run_tuning
    runner=measure_ctx.runner,
  File "/root/.local/lib/python3.8/site-packages/tvm-0.8.dev987+g21a7b498b-py3.8-linux-x86_64.egg/tvm/runtime/object.py", line 63, in __getattr__
    return _ffi_node_api.NodeGetAttr(self, name)
  File "tvm/_ffi/_cython/./packed_func.pxi", line 322, in tvm._ffi._cy3.core.PackedFuncBase.__call__
  File "tvm/_ffi/_cython/./packed_func.pxi", line 257, in tvm._ffi._cy3.core.FuncCall
  File "tvm/_ffi/_cython/./packed_func.pxi", line 246, in tvm._ffi._cy3.core.FuncCall3
  File "tvm/_ffi/_cython/./base.pxi", line 160, in tvm._ffi._cy3.core.CALL
TypeError: Traceback (most recent call last):
  3: TVMFuncCall
  2: _ZNSt17_Function_handlerI
  1: tvm::NodeGetAttr(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)
  0: tvm::ReflectionVTable::GetAttr(tvm::runtime::Object*, tvm::runtime::String const&) const
  File "/root/tvm/include/tvm/node/reflection.h", line 390
TypeError: auto_scheduler.RPCRunner is not registered via TVM_REGISTER_NODE_TYPE

**Comment by lllggghhh1** [comment]
> Hello, while building the tune_network_cuda.py ( Auto-scheduling a Neural Network for NVIDIA GPU)in TVM , I got the following error: TypeError: auto_scheduler.RPCRunner is not registered via TVM_REGISTER_NODE_TYPE
> 
> Could anyone help me ?

**Comment by roastduck** [comment]
Hi @lllggghhh1, have you solved the problem? I am encountering the same error.
