### ISSUE TITLE
Bug meshgrid

### ISSUE THREAD

**Issue by delldu** [apache/tvm#8378]
**1. Environment:**
1.1 The version of TVM you are using (e.g., the git commit hash of your source tree).
commit 8d4df91836bac8ee416adf29141d051c952802a7 (HEAD -> main, origin/main, origin/HEAD)

1.2 Which hardware and operating system version you are running TVM on.
AMD x86, ubuntu18.04

1.3 Which hardware device and OS you are targeting for your TVM compilation.
AMD x86, ubuntu18.04, only set(USE_LLVM ON) for config file.

1.4 Document
https://tvm.apache.org/docs/api/python/relay/index.html#tvm.relay.meshgrid

**2. Test code**
```
import tvm
from tvm import relay

x = [1, 2, 3]
y = [4, 5]

gx, gy = relay.meshgrid([x, y])
```

**3. Error message** 

```
Traceback (most recent call last):
  File "t.py", line 7, in <module>
    gx, gy = relay.meshgrid([x, y])
  File "/home/dell/ZDisk/Workspace/study/tvm/python/tvm/relay/op/transform.py", line 561, in meshgrid
    return TupleWrapper(_make.meshgrid(Tuple(data), indexing), ret_size)
  File "/home/dell/ZDisk/Workspace/study/tvm/python/tvm/relay/expr.py", line 194, in __init__
    self.__init_handle_by_constructor__(_ffi_api.Tuple, fields, span)
  File "/home/dell/ZDisk/Workspace/study/tvm/python/tvm/_ffi/_ctypes/object.py", line 136, in __init_handle_by_constructor__
    handle = __init_by_constructor__(fconstructor, args)
  File "/home/dell/ZDisk/Workspace/study/tvm/python/tvm/_ffi/_ctypes/packed_func.py", line 260, in __init_handle_by_constructor__
    raise get_last_ffi_error()
tvm._ffi.base.TVMError: Traceback (most recent call last):
  2: TVMFuncCall
  1: std::_Function_handler<void (tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*), tvm::runtime::TypedPackedFunc<tvm::relay::Tuple (tvm::runtime::Array<tvm::RelayExpr, void>, tvm::Span)>::AssignTypedLambda<tvm::relay::{lambda(tvm::runtime::Array<tvm::RelayExpr, void>, tvm::Span)#5}>(tvm::relay::{lambda(tvm::runtime::Array<tvm::RelayExpr, void>, tvm::Span)#5}, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)::{lambda(tvm::runtime::TVMArgs const&, tvm::runtime::TVMRetValue*)#1}>::_M_invoke(std::_Any_data const&, tvm::runtime::TVMArgs&&, tvm::runtime::TVMRetValue*&&)
  0: tvm::runtime::TVMMovableArgValueWithContext_::operator tvm::runtime::Array<tvm::RelayExpr, void><tvm::runtime::Array<tvm::RelayExpr, void> >() const
  3: TVMFuncCall
  2: std::_Function_handler<void (tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*), tvm::runtime::TypedPackedFunc<tvm::relay::Tuple (tvm::runtime::Array<tvm::RelayExpr, void>, tvm::Span)>::AssignTypedLambda<tvm::relay::{lambda(tvm::runtime::Array<tvm::RelayExpr, void>, tvm::Span)#5}>(tvm::relay::{lambda(tvm::runtime::Array<tvm::RelayExpr, void>, tvm::Span)#5}, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)::{lambda(tvm::runtime::TVMArgs const&, tvm::runtime::TVMRetValue*)#1}>::_M_invoke(std::_Any_data const&, tvm::runtime::TVMArgs&&, tvm::runtime::TVMRetValue*&&)
  1: tvm::runtime::TVMMovableArgValueWithContext_::operator tvm::runtime::Array<tvm::RelayExpr, void><tvm::runtime::Array<tvm::RelayExpr, void> >() const
  0: tvm::runtime::Array<tvm::RelayExpr, void> tvm::runtime::TVMPODValue_::AsObjectRef<tvm::runtime::Array<tvm::RelayExpr, void> >() const
  File "/home/dell/ZDisk/Workspace/study/tvm/include/tvm/runtime/packed_func.h", line 714
TVMError: In function relay.ir.Tuple: error while converting argument 0: [02:49:22] /home/dell/ZDisk/Workspace/study/tvm/include/tvm/runtime/packed_func.h:1591: 
---------------------------------------------------------------
An error occurred during the execution of TVM.
For more information, please see: https://tvm.apache.org/docs/errors.html
---------------------------------------------------------------
  Check failed: (!checked_type.defined()) is false: Expected Array[RelayExpr], but got Array[index 0: Array]


```

**Comment by ymwangg** [comment]
The document may be misleading. You need to compile the relay expression.
The following code should work.
```python
import tvm
from tvm import relay
from tvm.relay import create_executor

x = relay.var("x", shape=[3],dtype="int32")
y = relay.var("y", shape=[2],dtype="int32")
out = relay.meshgrid([x, y]).astuple()
f = relay.Function([x,y], out)
mod = tvm.IRModule.from_expr(f)
executor = create_executor(kind="graph", mod=mod, target="llvm")
res = executor.evaluate()(np.array([1,2,3]).astype("int32"), np.array([4,5]).astype("int32"))
print(res)
```
