### ISSUE TITLE
[Bug] AutoScheduler not work when kernel contains conv2d+gradient and has a large size 

### ISSUE THREAD

**Issue by kk2049** [apache/tvm#8991]
Hello:  
I am trying to generate source code of an operator which involves `conv2d_nchw` and `gradient`. I tried to achieve this with AutoScheduler, but the search period will fail when the operator has a relative large shape, and when the `task.apply_best(log_file)`  was run, it will crash and print `Cannot find any valid schedule for ["conv2d_layer"] in file conv2d.json`.   

To be exact, the program works well when the layer looks like:  
```
@auto_scheduler.register_workload
def conv2d_layer():
    x = tvm.te.placeholder((1,64,7,7), name='x')
    w1 = tvm.te.placeholder((64,64,3,3), name='w1')
    z1=topi.nn.conv2d_nchw(x,w1,(1,1),(1,1),dilation=1,out_dtype="float32")
    [dw1] = tvm.te.gradient(z1, [w1])
    return [x,w1,dw1]
```
but will fail when it looks like:
```
@auto_scheduler.register_workload
def conv2d_layer():
    x = tvm.te.placeholder((1,128,7,7), name='x')
    w1 = tvm.te.placeholder((128,128,3,3), name='w1')
    z1=topi.nn.conv2d_nchw(x,w1,(1,1),(1,1),dilation=1,out_dtype="float32")
    [dw1] = tvm.te.gradient(z1, [w1])
    return [x,w1,dw1]
```
the whole program looks like this.  
```
import os

import numpy as np
import tvm
from tvm import te, auto_scheduler, topi
from tvm.topi.testing import conv2d_nchw_python

@auto_scheduler.register_workload
def conv2d_layer():
    x = tvm.te.placeholder((1,128,7,7), name='x')
    w1 = tvm.te.placeholder((128,128,3,3), name='w1')
    z1=topi.nn.conv2d_nchw(x,w1,(1,1),(1,1),dilation=1,out_dtype="float32")
    [dw1] = tvm.te.gradient(z1, [w1])
    return [x,w1,dw1]

target = tvm.target.Target("cuda")

task = auto_scheduler.SearchTask(
    func=conv2d_layer, args=(), target=target
)


print("Computational DAG:")
print(task.compute_dag)

log_file = "conv2d.json"
measure_ctx = auto_scheduler.LocalRPCMeasureContext(min_repeat_ms=300)
tune_option = auto_scheduler.TuningOptions(
    num_measure_trials=1000,  # change this to 1000 to achieve the best performance
    runner=measure_ctx.runner,
    measure_callbacks=[auto_scheduler.RecordToFile(log_file)],
    verbose=2,
)
task.tune(tune_option)

sch, args = task.apply_best(log_file)

del measure_ctx

print("Lowered TIR:")
print(tvm.lower(sch, args, simple_mode=True))

print("CUDA source code:")
print(task.print_best(log_file, print_mode="cuda"))
```
the last part of debug message is below:
```
==================================================
No: 1000        GFLOPS: 0.00 / 0.00     results: MeasureResult(error_type:RuntimeDeviceError, error_msg:Traceback (most recent call last):
  File "/root/tvm/python/tvm/auto_scheduler/measure.py", line 1120, in _rpc_run
    random_fill(empty_array)
  File "/root/tvm/python/tvm/_ffi/_ctypes/packed_func.
...
----------
An error occurred during the execution of TVM.
For more information, please see: https://tvm.apache.org/docs/errors.html
---------------------------------------------------------------
  Check failed: (code == RPCCode::kReturn) is false: code=1
, all_cost:13.82, Tstamp:1631297770.85)
==================================================

..........

[18:16:10] /root/tvm/src/auto_scheduler/measure.cc:299: Warning: Too many errors happened during tuning. Switching to debug mode.

Time elapsed for measurement: 426.86 s
----------------------------------------------------------------------
------------------------------  [ Done ]
----------------------------------------------------------------------
No valid state found in this search round. Check if it has traversed all of the search space.
/root/anaconda3/lib/python3.6/site-packages/xgboost/training.py:17: UserWarning: Old style callback is deprecated.  See: https://xgboost.readthedocs.io/en/latest/python/callbacks.html
  warnings.warn(f'Old style callback is deprecated.  See: {link}', UserWarning)
MeasureInput with old format workload key ["conv2d_layer"] should be updated using the script from https://github.com/apache/tvm/pull/7317.
MeasureInput with old format workload key ["dense_layer"] should be updated using the script from https://github.com/apache/tvm/pull/7317.


Traceback (most recent call last):
  File "conv_layer_tuning_grad.py", line 38, in <module>
    sch, args = task.apply_best(log_file)
  File "/root/tvm/python/tvm/auto_scheduler/search_task.py", line 522, in apply_best
    "Cannot find any valid schedule for %s in file %s" % (self.workload_key, log_file)
RuntimeError: Cannot find any valid schedule for ["conv2d_layer"] in file conv2d.json
```
The commit id of my tvm build is:
```
commit f1ca91d4e401096d04e962c982d62b1f2669c9f5
Date:   Wed Aug 25 18:25:29 2021 -0700

```
I am wandering that what is wrong with it. Can anyone help me?

**Comment by comaniac** [comment]
You need to specify head when calculating the gradient:

```
x = tvm.te.placeholder((1,128,7,7), name='x')
w1 = tvm.te.placeholder((128,128,3,3), name='w1')
z1=topi.nn.conv2d_nchw(x,w1,(1,1),(1,1),dilation=1,out_dtype="float32")
dy = tvm.te.placeholder(z1.shape, name="dy")
[dw1] = tvm.te.gradient(z1, [w1], head=dy)
```

According to https://github.com/apache/tvm/blob/main/python/tvm/te/autodiff.py#L33, if head is None, then the identity tensor of shape `output.shape + output.shape` will be used. It means the size of `dy` will be super large and unlikely to fit into the GPU memory.

**Comment by kk2049** [comment]
That really works! I do met a few more bugs like timeout at runtime but they are quiet easy to fix. Thanks a lot!

**Comment by gbxu** [comment]
Weird. When I use auto_scheduler to search conv2d on V100, it shows "No valid state found in this search round. Check if it has traversed all of the search space." and lots of messages like
```
No: 3	GFLOPS: 0.00 / 0.00	results: MeasureResult(error_type:RuntimeDeviceError, error_msg:Traceback (most recent call last):
  File "/home/test/tvm/python/tvm/auto_scheduler/measure.py", line 1124, in _rpc_run
    random_fill(empty_array)
  File "/home/test/tvm/python/tvm/_ffi/_ctypes/packed_func.py", line 237, in __call__
    rai
...
----------
An error occurred during the execution of TVM.
```
My workload is as follows.
```
@auto_scheduler.register_workload
def my_workload():
    A = tvm.te.placeholder((128, 64, 224, 224), name='input0')
    W = tvm.te.placeholder((64, 64, 3, 3), name='input1')
    C = topi.nn.conv2d(A, W, (1,1), (1,1), (1,1), layout='NCHW', out_dtype=A.dtype) # (128, 64, 224, 224)
        return [A, W, C]
```

After setting MAX_TRACEBACK_INFO_LEN=8192, I can get more details:
```
Get 64 programs to measure:
........................................................
*E*E*E*E*E*E*E*E*E*E*E*E*E*E*E*E*E*E*E*E*E*E*E*E*E*E*E*E*E*E*E*E*E*E*E*E*E*E*E*E*E*E*E*E*E*E*E*E*E*E*E*E*E*E*E*E==================================================
No: 1	GFLOPS: 0.00 / 0.00	results: MeasureResult(error_type:RuntimeDeviceError, error_msg:Traceback (most recent call last):
  File "/home/test/tvm/python/tvm/auto_scheduler/measure.py", line 1124, in _rpc_run
    random_fill(empty_array)
  File "/home/test/tvm/python/tvm/_ffi/_ctypes/packed_func.py", line 237, in __call__
    raise get_last_ffi_error()
tvm._ffi.base.TVMError: Traceback (most recent call last):
  4: TVMFuncCall
  3: _ZNSt17_Function_handlerIFvN3tvm7runtime7TVMArgsEPNS1_11
  2: tvm::runtime::RPCWrappedFunc::operator()(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*) const
  1: tvm::runtime::RPCClientSession::CallFunc(void*, TVMValue const*, int const*, int, std::function<void (tvm::runtime::TVMArgs)> const&)
  0: tvm::runtime::RPCEndpoint::CallFunc(void*, TVMValue const*, int const*, int, std::function<void (tvm::runtime::TVMArgs)>)
  File "/home/test/tvm/src/runtime/rpc/rpc_endpoint.cc", line 801
TVMError: 
---------------------------------------------------------------
An error occurred during the execution of TVM.
For more information, please see: https://tvm.apache.org/docs/errors.html
---------------------------------------------------------------
  Check failed: (code == RPCCode::kReturn) is false: code=kShutdown

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/test/tvm/python/tvm/auto_scheduler/measure.py", line 1185, in _rpc_run_worker
    res = _rpc_run(*args)
  File "/home/test/tvm/python/tvm/auto_scheduler/measure.py", line 1143, in _rpc_run
    dev.free_raw_stream(stream)
  File "/home/test/tvm/python/tvm/_ffi/runtime_ctypes.py", line 456, in free_raw_stream
    check_call(_LIB.TVMStreamFree(self.device_type, self.device_id, stream))
  File "/home/test/tvm/python/tvm/_ffi/base.py", line 348, in check_call
    raise get_last_ffi_error()
tvm._ffi.base.TVMError: Traceback (most recent call last):
  42: 0xffffffffffffffff
  41: _start
  40: __libc_start_main
  39: main
  38: Py_Main
  37: 0x000000000063886a
  36: PyObject_Call
  35: 0x000000000058945c
  34: 0x0000000000507cd3
  33: _PyEval_EvalFrameDefault
  32: 0x000000000050a3fc
  31: 0x00000000005099ff
  30: 0x0000000000507cd3
  29: _PyEval_EvalFrameDefault
  28: 0x000000000050a22e
  27: 0x0000000000516284
  26: 0x0000000000507cd3
  25: _PyEval_EvalFrameDefault
  24: 0x000000000050a3fc
  23: 0x00000000005099ff
  22: 0x0000000000507cd3
  21: _PyEval_EvalFrameDefault
  20: PyObject_Call
  19: 0x00000000005893d9
  18: 0x0000000000507cd3
  17: _PyEval_EvalFrameDefault
  16: PyObject_Call
  15: 0x000000000058931a
  14: 0x0000000000507cd3
  13: _PyEval_EvalFrameDefault
  12: 0x000000000050a3fc
  11: 0x00000000005096c7
  10: _PyEval_EvalFrameDefault
  9: 0x000000000050a532
  8: _PyObject_FastCallKeywords
  7: 0x00007f2b9b1f5c12
  6: _ctypes_callproc
  5: ffi_call
  4: ffi_call_unix64
  3: TVMStreamFree
  2: tvm::runtime::RPCDeviceAPI::FreeStream(DLDevice, void*)
  1: non-virtual thunk to tvm::runtime::RPCClientSession::FreeStream(DLDevice, void*)
  0: std::_Function_handler<void (tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*), tvm::runtime::RPCEndpoint::Init()::{lambda(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)#2}>::_M_invoke(std::_Any_data const&, tvm::runtime::TVMArgs&&, tvm::runtime::TVMRetValue*&&)
  File "/home/test/tvm/src/runtime/rpc/rpc_endpoint.cc", line 681
TVMError: 
---------------------------------------------------------------
An error occurred during the execution of TVM.
For more information, please see: https://tvm.apache.org/docs/errors.html
---------------------------------------------------------------
  Check failed: (code == RPCCode::kReturn) is false: code=1
, all_cost:11.04, Tstamp:1636202883.20)
==================================================
Placeholder: input0, input1
blockIdx.x nn.0@ff.0@yy.0@xx.0@ (0,16384)
  vthread nn.1@ff.1@yy.1@xx.1@ (0,4)
    threadIdx.x nn.2@ff.2@yy.2@xx.2@ (0,64)
      for rc.0 (0,64)
        for rx.0 (0,3)
          threadIdx.x ax0@ax1@ax2@ax3@.0.1 (0,64)
            input1.shared = ...
          for ax0@ax1@ax2@ax3@.0.0 (0,126)
            threadIdx.x ax0@ax1@ax2@ax3@.0.1 (0,64)
              pad_temp.shared = ...
          for ry.1 (0,3)
            for nn_c.3 (0,2)
              for yy_c.4 (0,7)
                for xx_c.4 (0,7)
                  compute.local = ...
      for nn.3 (0,2)
        for yy.3 (0,7)
          for xx.3 (0,7)
            compute = ...

==================================================

```
hi, @comaniac . Is it due to the large problem size of conv2d?  I think it's a common setting of CNN model.

**Comment by comaniac** [comment]
It's not due to the large problem size. Did you set USE_RANDOM ON when building TVM?

For future discussions of this issue, please post to the discuss forum.

**Comment by gbxu** [comment]
> It's not due to the large problem size. Did you set USE_RANDOM ON when building TVM?
> 
> For future discussions of this issue, please post to the discuss forum.

Sure. --> https://discuss.tvm.apache.org/t/autoscheduler-failed-to-find-a-valid-schedule/11001
