### ISSUE TITLE
[Bug] RPC.getApi("ServerLoop") returns null

### ISSUE THREAD

**Issue by pfk-beta** [apache/tvm#9587]
### Expected behavior

RPC server on android works correctly, i.e. tuning models from another machine can run successfully.

### Actual behavior

Cannot run autotuning.

### Environment

Ubuntu 20.04, tvm git hash: 99b9d4276f083d407a7f2afbf68141ac81ba001a. Target device: android aarch64, api 30
Any environment details, such as: Operating System, TVM version, etc

### Steps to reproduce
build tvm:
```
cp ../cmake/config.cmake .

sed -i 's/set(USE_LLVM OFF)/set(USE_LLVM llvm-config-12)/g' config.cmake

cmake .. \
    -DUSE_RPC=ON \
    -DUSE_CPP_RPC=ON \
    -DUSE_IOS_RPC=ON

TVM_BUILD_PATH=tvm/build-sys-llvm12 make -j4
```

In `NativeServerLoop.run` before calling `serverLoop.pushArg(fsend).pushArg(frecv).invoke();`, paste `      Log.d("NativeServerLoop", "serverLoop == null: " + (serverLoop == null));`

**Comment by pfk-beta** [comment]
I think that there should be at least simple condition against NullPointerException with error message.

**Comment by pfk-beta** [comment]
```
2021-11-25 14:01:50.977 20632-20666/org.apache.tvm.deploy_segment D/NativeServerLoop: serverLoop == null: true
2021-11-25 14:01:50.978 20632-20666/org.apache.tvm.deploy_segment W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'org.apache.tvm.Function org.apache.tvm.Function.pushArg(org.apache.tvm.Function)' on a null object reference
2021-11-25 14:01:50.978 20632-20666/org.apache.tvm.deploy_segment W/System.err:     at org.apache.tvm.rpc.NativeServerLoop.run(NativeServerLoop.java:59)
2021-11-25 14:01:50.978 20632-20666/org.apache.tvm.deploy_segment W/System.err:     at org.apache.tvm.rpc.ConnectTrackerServerProcessor.run(ConnectTrackerServerProcessor.java:168)
2021-11-25 14:01:50.978 20632-20666/org.apache.tvm.deploy_segment W/System.err:     at org.apache.tvm.deploy_segment.RPCProcessor.run(RPCProcessor.java:56)
```

**Comment by pfk-beta** [comment]
@yzhliu I can see that you have contributed a lot of code to TVM, especially to rpc module. So big thanks to you. Can I have a few questions to you? These quenstions would help me to understand how tvm works with RPC.

**Comment by pfk-beta** [comment]
additional missing header: rpc_server_env.cc - it required for uploaing module
