### ISSUE TITLE
[Bug] "KeyError: 'arduino_cli_cmd'" on `tvmc micro create ... arduino` 

### ISSUE THREAD

**Issue by gromero** [apache/tvm#9607]
### Expected behavior

```
$ tvmc micro create --force /tmp/x9584 ~/scripts/sine.tar arduino --project-option project_type=host_driven
```
This `tvmc` command should finish without any error, correctly generating a project dir in `/tmp/x9584`

### Actual behavior

```
gromero@amd:~/git/tvm$ tvmc micro create --force /tmp/x9584 ~/scripts/sine.tar arduino --project-option project_type=host_driven 
[19:01:56] /home/gromero/git/tvm/src/target/target_kind.cc:191: Warning: Unable to detect CUDA version, default to "-mcpu=sm_20" instead
[19:01:56] /home/gromero/git/tvm/src/target/target_kind.cc:217: Warning: Unable to detect ROCm compute arch, default to "-mcpu=gfx900" instead
[19:01:56] /home/gromero/git/tvm/src/target/target_kind.cc:231: Warning: Unable to detect ROCm version, assuming >= 3.5
[19:01:56] /home/gromero/git/tvm/src/target/target_kind.cc:163: Warning: Unable to detect CUDA version, default to "-arch=sm_20" instead
[19:01:56] /home/gromero/git/tvm/src/target/target_kind.cc:191: Warning: Unable to detect CUDA version, default to "-mcpu=sm_20" instead
[19:01:56] /home/gromero/git/tvm/src/target/target_kind.cc:217: Warning: Unable to detect ROCm compute arch, default to "-mcpu=gfx900" instead
[19:01:56] /home/gromero/git/tvm/src/target/target_kind.cc:231: Warning: Unable to detect ROCm version, assuming >= 3.5
[19:01:56] /home/gromero/git/tvm/src/target/target_kind.cc:163: Warning: Unable to detect CUDA version, default to "-arch=sm_20" instead
The following error occured on the Project API server side: 
 calling method generate_project: JSON-RPC error # -32000: calling method generate_project
Traceback (most recent call last):
  File "/home/gromero/git/tvm/python/tvm/micro/project_api/server.py", line 481, in serve_one_request  # <--- Outermost server-side stack frame
    self._dispatch_request(request)
  File "/home/gromero/git/tvm/python/tvm/micro/project_api/server.py", line 593, in _dispatch_request
    return_value = dispatch_method(**params)
  File "/home/gromero/git/tvm/python/tvm/micro/project_api/server.py", line 621, in _dispatch_generate_project
    return self._handler.generate_project(
  File "/home/gromero/git/tvm/build/microtvm_template_projects/arduino/microtvm_api_server.py", line 320, in generate_project
    version = self._get_platform_version(options["arduino_cli_cmd"])
KeyError: 'arduino_cli_cmd'
```

### Environment

Any if `USE_MICRO` and `tvmc` is enabled/installed

### Steps to reproduce

`$ tvmc micro create <any_tmp_project_dir> <path_to_a_compiled_model_saved_as_MLF> arduino --project-option project_type=host_driven`

**Comment by gromero** [comment]
This happens because even if `arduino_cli_cmd` option in `PROJECT_OPTIONS` has not `"generate_project"` listed in `required`  list.

**Comment by mehrdadh** [comment]
@gromero I think this is fixed now?

**Comment by gromero** [comment]
@mehrdadh absolutely. Thanks for the ping and sorry leaving it opened : )

I'm closing since it's fixed by https://github.com/apache/tvm/pull/9584
