### ISSUE TITLE
[TVMC][MicroTVM] tvmc micro `project_dir` arg does not accept relative path 

### ISSUE THREAD

**Issue by mehrdadh** [apache/tvm#9661]
### Expected behavior

Expect `tvmc micro create-project` to run without error.

### Actual behavior
```bash
The following error occured on the Project API server side: 
 calling method generate_project: JSON-RPC error # -32000: calling method generate_project
Traceback (most recent call last):
  File "/home/mhessar/tvm/python/tvm/micro/project_api/server.py", line 481, in serve_one_request  # <--- Outermost server-side stack frame
    self._dispatch_request(request)
  File "/home/mhessar/tvm/python/tvm/micro/project_api/server.py", line 593, in _dispatch_request
    return_value = dispatch_method(**params)
  File "/home/mhessar/tvm/python/tvm/micro/project_api/server.py", line 625, in _dispatch_generate_project
    options,
  File "/home/mhessar/tvm/build/microtvm_template_projects/arduino/microtvm_api_server.py", line 338, in generate_project
    project_dir.mkdir()
  File "/usr/lib/python3.6/pathlib.py", line 1248, in mkdir
    self._accessor.mkdir(self, mode)
  File "/usr/lib/python3.6/pathlib.py", line 387, in wrapped
    return strfunc(str(pathobj), *args)
FileNotFoundError: [Errno 2] No such file or directory: 'tvmc_relative_path_test/project'
```

### Steps to reproduce
```python
poetry run tvmc micro create-project ./tvmc_relative_path_test ./output_dir/model.tar arduino --project-option "project_type=host_driven"
```

cc @gromero @guberti

**Comment by mehrdadh** [comment]
fixed by https://github.com/apache/tvm/pull/9663
