### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by CrazyKing5023** [apache/tvm#9779]
### Expected behavior
run hexagon sim on x86 

pytest -v tests/python/contrib/test_hexagon/test_maxpool2d_blocked.py::TestMaxPooling

### Actual behavior

/usr/bin/pytest:7: TargetDeprecatedDeprecationWarning: [logilab.common.pytest] [logilab-common 1.3] logilab-pytest is deprecated, use another test runner
  run()
going into /xxx/project/work_space/dmlc/tvm/tests
Traceback (most recent call last):
  File "/xxx/.local/lib/python3.8/site-packages/logilab/common/pytest.py", line 744, in run
    cmd(*args)
  File "/xxx/.local/lib/python3.8/site-packages/logilab/common/pytest.py", line 359, in testall
    if not self.testonedir(dirname, exitfirst):
  File "/xxx/.local/lib/python3.8/site-packages/logilab/common/pytest.py", line 397, in testonedir
    remove_local_modules_from_sys(testdir)
  File "/xxx/.local/lib/python3.8/site-packages/logilab/common/pytest.py", line 315, in remove_local_modules_from_sys
    if not osp.isabs(modfile) or modfile.startswith(testdir):
  File "/usr/local/python3/lib/python3.8/posixpath.py", line 62, in isabs
    s = os.fspath(s)
TypeError: expected str, bytes or os.PathLike object, not NoneType
*******************************************************************************

### Environment

ubuntu16.04、python3.8、tvm main

### Steps to reproduce

Preferably a minimal script to cause the issue to occur.

**Comment by driazati** [comment]
running this test in the hexagon docker image seems to work: `python tests/scripts/ci.py hexagon --tests tests/python/contrib/test_hexagon/test_maxpool2d_blocked.py::TestMaxPooling`, so closing this issue. please feel free to re-open it if you're still seeing this failure on the latest commit from `main`
